package emr.system;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import emr.system.classes.Diagnosis; 

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SARAVANAPRIYA
 */
public class DiagnosisForm extends javax.swing.JFrame {

    /**
     * Creates new form DiagnosisFrame
     */
    public DiagnosisForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customPanelButton4 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton5 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton6 = new emr.system.customComponents.CustomPanelButton();
        panelRound1 = new emr.system.PanelRound();
        symptoms1 = new javax.swing.JLabel();
        diagnosisNameTextField = new javax.swing.JTextField();
        diagnosisName = new javax.swing.JLabel();
        diagnosisDate = new javax.swing.JLabel();
        diagnosisDateTextField = new javax.swing.JTextField();
        symptoms = new javax.swing.JLabel();
        symptomsTextField = new javax.swing.JTextField();
        riskTextField = new javax.swing.JTextField();
        customPanelButton1 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton2 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton3 = new emr.system.customComponents.CustomPanelButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new emr.system.customComponents.CustomTable();
        symptoms2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        symptoms3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 800));
        setPreferredSize(new java.awt.Dimension(1300, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 800));

        jPanel1.setBackground(new java.awt.Color(255, 254, 238));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customPanelButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139), 2));
        customPanelButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/homeIcon.png"))); // NOI18N
        customPanelButton4.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(customPanelButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 30, -1, -1));

        customPanelButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139), 2));
        customPanelButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/infoIcon.png"))); // NOI18N
        customPanelButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(customPanelButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 100, -1, -1));

        customPanelButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139), 2));
        customPanelButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/logOffIcon.png"))); // NOI18N
        customPanelButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(customPanelButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 170, -1, -1));

        panelRound1.setBackground(new java.awt.Color(211, 221, 255));

        symptoms1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        symptoms1.setForeground(new java.awt.Color(0, 0, 139));
        symptoms1.setText("Risk:");

        diagnosisNameTextField.setBackground(new java.awt.Color(255, 254, 238));
        diagnosisNameTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        diagnosisNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosisNameTextFieldActionPerformed(evt);
            }
        });

        diagnosisName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diagnosisName.setForeground(new java.awt.Color(0, 0, 139));
        diagnosisName.setText("Diagnosis Name:");

        diagnosisDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diagnosisDate.setForeground(new java.awt.Color(0, 0, 139));
        diagnosisDate.setText("Diagnosis Date:");

        diagnosisDateTextField.setBackground(new java.awt.Color(255, 254, 238));
        diagnosisDateTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        diagnosisDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosisDateTextFieldActionPerformed(evt);
            }
        });

        symptoms.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        symptoms.setForeground(new java.awt.Color(0, 0, 139));
        symptoms.setText("Symptoms: ");

        symptomsTextField.setBackground(new java.awt.Color(255, 254, 238));
        symptomsTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        symptomsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symptomsTextFieldActionPerformed(evt);
            }
        });

        riskTextField.setBackground(new java.awt.Color(255, 254, 238));
        riskTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        riskTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskTextFieldActionPerformed(evt);
            }
        });

        customPanelButton1.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton1.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton1.setText(" A D D ");
        customPanelButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customPanelButton1.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton1.setRadius(25);
        customPanelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton1ActionPerformed(evt);
            }
        });

        customPanelButton2.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton2.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton2.setText("E D I T");
        customPanelButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customPanelButton2.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton2.setRadius(25);
        customPanelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton2ActionPerformed(evt);
            }
        });

        customPanelButton3.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton3.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton3.setText("R E F R E S H");
        customPanelButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customPanelButton3.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton3.setRadius(25);
        customPanelButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diagnosisDate)
                    .addComponent(symptoms1)
                    .addComponent(diagnosisName))
                .addGap(29, 29, 29)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(diagnosisNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(symptomsTextField)
                    .addComponent(diagnosisDateTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRound1Layout.createSequentialGroup()
                            .addComponent(symptoms)
                            .addGap(18, 18, 18)
                            .addComponent(riskTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(136, 136, 136)
                            .addComponent(customPanelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(customPanelButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(customPanelButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diagnosisDate)
                            .addComponent(diagnosisDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(diagnosisNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(riskTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(diagnosisName)
                            .addComponent(symptoms)))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(customPanelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(symptoms1)
                            .addComponent(symptomsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(customPanelButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customPanelButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 1040, 350));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 1040, 160));

        symptoms2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        symptoms2.setForeground(new java.awt.Color(0, 0, 139));
        symptoms2.setText("ADD DIAGNOSIS");
        jPanel1.add(symptoms2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/diagnosisIcon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 570, 90));

        symptoms3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        symptoms3.setForeground(new java.awt.Color(0, 0, 139));
        symptoms3.setText("DIAGNOSIS HISTORY");
        jPanel1.add(symptoms3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void diagnosisDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosisDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diagnosisDateTextFieldActionPerformed

    private void symptomsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symptomsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_symptomsTextFieldActionPerformed

    private void diagnosisNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosisNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diagnosisNameTextFieldActionPerformed

    private void riskTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riskTextFieldActionPerformed

    private void customPanelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton1ActionPerformed
        String value1 = "001";
        String value2 = diagnosisDateTextField.getText();
        String value3 = symptomsTextField.getText();
        String value4 = diagnosisNameTextField.getText();
        String value5 = riskTextField.getText();
        

        Diagnosis diagnosis1 = new Diagnosis(value1, value2, value3, value4, value5);

        //Construct a string with the combined values
        String adding = "\n" + diagnosis1.getPatientID()+ "," + diagnosis1.getDiagnosisDate()+ "," + diagnosis1.getSymptoms() + "," + diagnosis1.getDiagnosisName() + "," + diagnosis1.getRisk();

        //Write the combined values to a file
        String filePath = "C:\\Users\\SARAVANAPRIYA\\OneDrive\\Documents\\Sem 2\\AP\\GA\\Part B\\Diagnosis.txt";
        try {
            //Write "adding" string to a file at the specified file path
            Files.write(Paths.get(filePath), adding.getBytes(), StandardOpenOption.APPEND);

        } catch (IOException ex) {
            //If an exception occurs during the file writing process, print the stack trace
            ex.printStackTrace();
        }
    }//GEN-LAST:event_customPanelButton1ActionPerformed

    private void customPanelButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton2ActionPerformed
         String filePath = "C:\\Users\\SARAVANAPRIYA\\OneDrive\\Documents\\Sem 2\\AP\\GA\\Part B\\Diagnosis.txt";
        File file = new File(filePath);

        try{
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            //Write the column names as the first line
            bw.write("patientID,diagnosisDate,symptoms,diagnosisName,risk");
            bw.newLine();

            //Wrtie each row of the table to the file
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                for (int j = 0; j < jTable1.getColumnCount(); j++) {
                    Object value = jTable1.getValueAt(i, j);
                    if (value != null) {
                        bw.write(value.toString());
                    }
                    bw.write(",");
                }
                bw.newLine();
            }
            bw.close();
            fw.close();

        }
        catch(IOException ex){
            //If an IOException occurs during the file writing process, print error message
            System.out.println("Errror");
        }
    }//GEN-LAST:event_customPanelButton2ActionPerformed

    private void customPanelButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton3ActionPerformed
     //File path to read the data
        String filePath = "C:\\Users\\SARAVANAPRIYA\\OneDrive\\Documents\\Sem 2\\AP\\GA\\Part B\\Diagnosis.txt";
        File file = new File(filePath);

        try {
            //Reading the file
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
            //Setting up the table model
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setColumnIdentifiers(columnsName);
            model.setRowCount(0);
            //Populate the table model with data
            Object[] tableLines = br.lines().toArray();
            for (int i = 0; i < tableLines.length; i++){
                String line= tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);
            }

        } catch (Exception ex) {
            //If an exception occurs during the file reading process, log the exception details
            Logger.getLogger(DiagnosisForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_customPanelButton3ActionPerformed

    private void customPanelButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton4ActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_customPanelButton4ActionPerformed

    private void customPanelButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton5ActionPerformed
        new MedicalHistoryForm().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_customPanelButton5ActionPerformed

    private void customPanelButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton6ActionPerformed
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customPanelButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagnosisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagnosisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagnosisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagnosisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiagnosisForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private emr.system.customComponents.CustomPanelButton customPanelButton1;
    private emr.system.customComponents.CustomPanelButton customPanelButton2;
    private emr.system.customComponents.CustomPanelButton customPanelButton3;
    private emr.system.customComponents.CustomPanelButton customPanelButton4;
    private emr.system.customComponents.CustomPanelButton customPanelButton5;
    private emr.system.customComponents.CustomPanelButton customPanelButton6;
    private javax.swing.JLabel diagnosisDate;
    private javax.swing.JTextField diagnosisDateTextField;
    private javax.swing.JLabel diagnosisName;
    private javax.swing.JTextField diagnosisNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private emr.system.customComponents.CustomTable jTable1;
    private emr.system.PanelRound panelRound1;
    private javax.swing.JTextField riskTextField;
    private javax.swing.JLabel symptoms;
    private javax.swing.JLabel symptoms1;
    private javax.swing.JLabel symptoms2;
    private javax.swing.JLabel symptoms3;
    private javax.swing.JTextField symptomsTextField;
    // End of variables declaration//GEN-END:variables
}
