/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emr.system;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Rayyan
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }
    
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customButton4 = new emr.system.customComponents.CustomButton();
        logoLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        customButton2 = new emr.system.customComponents.CustomButton();
        password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        customPanelButton1 = new emr.system.customComponents.CustomPanelButton();

        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1300, 800));
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setBackground(new java.awt.Color(0, 102, 51));
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/emrLogoIcon.jpg"))); // NOI18N
        logoLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 3, new java.awt.Color(0, 0, 139)));
        getContentPane().add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        backgroundLabel.setBackground(new java.awt.Color(255, 254, 238));
        backgroundLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 0, 139)));
        backgroundLabel.setMaximumSize(new java.awt.Dimension(600, 600));
        backgroundLabel.setMinimumSize(new java.awt.Dimension(600, 600));
        backgroundLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 139));
        jLabel2.setText("Login ");
        backgroundLabel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 139));
        jLabel1.setText("Enter StaffId or Username");
        backgroundLabel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 184, -1));

        jLabel3.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 139));
        jLabel3.setText("Password");
        backgroundLabel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 302, 188, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 139));
        jLabel6.setText("or");
        backgroundLabel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        usernameTextField.setBackground(new java.awt.Color(211, 221, 255));
        usernameTextField.setText("doctor001");
        usernameTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        backgroundLabel.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 230, 26));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/WorkAccountLogo.png"))); // NOI18N
        backgroundLabel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, 30));

        customButton2.setText("      Use Microsoft Work Account");
        customButton2.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        customButton2.setOutlineColor(new java.awt.Color(204, 204, 204));
        customButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton2ActionPerformed(evt);
            }
        });
        backgroundLabel.add(customButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 230, 30));

        password.setBackground(new java.awt.Color(211, 221, 255));
        password.setText("123");
        password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        backgroundLabel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 230, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/profileIcon.jpg"))); // NOI18N
        backgroundLabel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 190, 140));

        customPanelButton1.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton1.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton1.setText("Login");
        customPanelButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customPanelButton1.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton1.setRadius(25);
        customPanelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton1ActionPerformed(evt);
            }
        });
        backgroundLabel.add(customPanelButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 230, 30));

        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 660, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton2ActionPerformed
        usernameTextField.setText("doctor001@staff.med");
        password.setText("123"); 
    }//GEN-LAST:event_customButton2ActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void customPanelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton1ActionPerformed
String pharmaUsername = "pharmacist001";
String pharmaPw = "123"; 

String doctorUsername1 = "doctor001"; 
String doctorPw1 = "123"; 

String doctorEmail = "doctor001@staff.med"; 
String doctorEmailPassword = "123"; 

String enteredUsername = usernameTextField.getText(); 
String enteredPassword = password.getText(); 


if(enteredUsername.equals(doctorUsername1) && enteredPassword.equals(doctorPw1)){
    new LandingPage().setVisible(true);
    this.dispose();
    

}
else if(enteredUsername.equals(pharmaUsername) && enteredPassword.equals(pharmaPw)){
    new LandingPage().setVisible(true);
    this.dispose();
    
}
else if(enteredUsername.equals(doctorEmail) && enteredPassword.equals(doctorEmailPassword)){
    new LandingPage().setVisible(true);
    this.dispose();
    
}
else{
    JOptionPane.showMessageDialog(null,"Invalid login details, Please try again"); 


} 
    }//GEN-LAST:event_customPanelButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundLabel;
    private emr.system.customComponents.CustomButton customButton2;
    private emr.system.customComponents.CustomButton customButton4;
    private emr.system.customComponents.CustomPanelButton customPanelButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPasswordField password;
    public javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
