/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emr.system;

/**
 *
 * @author Rayyan
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        customPanelButton1 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton2 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton3 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton4 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton5 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton6 = new emr.system.customComponents.CustomPanelButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 800));
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setPreferredSize(new java.awt.Dimension(1300, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 254, 238));
        jPanel1.setMaximumSize(new java.awt.Dimension(750, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 800));
        jPanel1.setRequestFocusEnabled(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/mainMenuIcon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customPanelButton1.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton1.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton1.setText("P A T I E N T  I N F O R M A T I O N");
        customPanelButton1.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton1.setRadius(20);
        customPanelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(customPanelButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 230, 30));

        customPanelButton2.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton2.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton2.setText("M E D I C A L  H I S T O R Y");
        customPanelButton2.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton2.setRadius(20);
        customPanelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(customPanelButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 230, 30));

        customPanelButton3.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton3.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton3.setText("T R E A T M E N T  C O U R S E");
        customPanelButton3.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton3.setRadius(20);
        customPanelButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(customPanelButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 230, 40));

        customPanelButton4.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton4.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton4.setText("P R O C E D U R E  &  M E D I C I N E");
        customPanelButton4.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton4.setRadius(20);
        customPanelButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(customPanelButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 230, 30));

        customPanelButton5.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton5.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton5.setText("D I A G N O S I S");
        customPanelButton5.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton5.setRadius(20);
        customPanelButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(customPanelButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 230, 30));

        customPanelButton6.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton6.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton6.setText("A N A L Y S I S");
        customPanelButton6.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton6.setRadius(20);
        customPanelButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(customPanelButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 230, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/dnaStrandIcon.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 560, 800));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 0, 550, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customPanelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton1ActionPerformed

    new PatientInfoForm().setVisible(true);
    this.dispose();

       
    }//GEN-LAST:event_customPanelButton1ActionPerformed

    private void customPanelButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton6ActionPerformed
    new AnalysisForm().setVisible(true); 
    this.dispose();
        
    }//GEN-LAST:event_customPanelButton6ActionPerformed

    private void customPanelButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton4ActionPerformed
    new ProcedureAndMedicineForm().setVisible(true); 
    this.dispose();
      
    }//GEN-LAST:event_customPanelButton4ActionPerformed

    private void customPanelButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton2ActionPerformed
    new MedicalHistoryForm().setVisible(true); 
    this.dispose(); 
      
    }//GEN-LAST:event_customPanelButton2ActionPerformed

    private void customPanelButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton5ActionPerformed
    new DiagnosisForm().setVisible(true); 
    this.dispose(); 
    }//GEN-LAST:event_customPanelButton5ActionPerformed

    private void customPanelButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton3ActionPerformed
    new TreatmentCourseForm().setVisible(true); 
    this.dispose(); 
    }//GEN-LAST:event_customPanelButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private emr.system.customComponents.CustomPanelButton customPanelButton1;
    private emr.system.customComponents.CustomPanelButton customPanelButton2;
    private emr.system.customComponents.CustomPanelButton customPanelButton3;
    private emr.system.customComponents.CustomPanelButton customPanelButton4;
    private emr.system.customComponents.CustomPanelButton customPanelButton5;
    private emr.system.customComponents.CustomPanelButton customPanelButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
