/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emr.system;

import emr.system.classes.MedicalForm;
import emr.system.classes.Vaccine;
import emr.system.classes.Disease;
import emr.system.classes.Allergy;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;



public class MedicalHistoryForm extends javax.swing.JFrame {

    /**
     * Creates new form PatientMedicalForm
     */
    public MedicalHistoryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelRound4 = new emr.system.PanelRound();
        durationTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        providerTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        medicineNameTextField = new javax.swing.JTextField();
        problemTextField = new javax.swing.JTextField();
        timeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        outcomeTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        wardedRadioButton1 = new javax.swing.JRadioButton();
        wardedRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        daysTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        wardNumberTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        majorComplicationTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        resultsTextField = new javax.swing.JTextField();
        panelRound1 = new emr.system.PanelRound();
        reactionTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        allergyTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        allergiesRadioButton3 = new javax.swing.JRadioButton();
        allergiesRadioButton4 = new javax.swing.JRadioButton();
        panelRound2 = new emr.system.PanelRound();
        nameOfVaccineTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        vaccineRadioButton5 = new javax.swing.JRadioButton();
        vaccineRadioButton6 = new javax.swing.JRadioButton();
        panelRound3 = new emr.system.PanelRound();
        diseaseTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        customPanelButton1 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton2 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton3 = new emr.system.customComponents.CustomPanelButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new emr.system.customComponents.CustomTable();
        jLabel1 = new javax.swing.JLabel();
        customPanelButton4 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton5 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton6 = new emr.system.customComponents.CustomPanelButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 254, 238));
        setMaximumSize(new java.awt.Dimension(1300, 800));
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setSize(new java.awt.Dimension(1300, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 254, 238));
        jPanel1.setForeground(new java.awt.Color(0, 0, 139));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound4.setBackground(new java.awt.Color(211, 221, 255));

        durationTextField.setBackground(new java.awt.Color(255, 254, 238));
        durationTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        durationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationTextFieldActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(0, 0, 139));
        jLabel13.setText("Major Complication :");

        jLabel2.setForeground(new java.awt.Color(0, 0, 139));
        jLabel2.setText("Date :");

        dateTextField.setBackground(new java.awt.Color(255, 254, 238));
        dateTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        providerTextField.setBackground(new java.awt.Color(255, 254, 238));
        providerTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        providerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providerTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 139));
        jLabel4.setText("Provider :");

        jLabel9.setForeground(new java.awt.Color(0, 0, 139));
        jLabel9.setText("Medicine Name :");

        medicineNameTextField.setBackground(new java.awt.Color(255, 254, 238));
        medicineNameTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        medicineNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineNameTextFieldActionPerformed(evt);
            }
        });

        problemTextField.setBackground(new java.awt.Color(255, 254, 238));
        problemTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        problemTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                problemTextFieldActionPerformed(evt);
            }
        });

        timeTextField.setBackground(new java.awt.Color(255, 254, 238));
        timeTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        timeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 139));
        jLabel3.setText("Time :");

        jLabel11.setForeground(new java.awt.Color(0, 0, 139));
        jLabel11.setText("Problem :");

        jLabel10.setForeground(new java.awt.Color(0, 0, 139));
        jLabel10.setText("Duration :");

        outcomeTextField.setBackground(new java.awt.Color(255, 254, 238));
        outcomeTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        outcomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outcomeTextFieldActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(0, 0, 139));
        jLabel14.setText("Does the patient need to be warded :");

        buttonGroup1.add(wardedRadioButton1);
        wardedRadioButton1.setForeground(new java.awt.Color(0, 0, 139));
        wardedRadioButton1.setText("YES");
        wardedRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardedRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(wardedRadioButton2);
        wardedRadioButton2.setForeground(new java.awt.Color(0, 0, 139));
        wardedRadioButton2.setText("NO");
        wardedRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardedRadioButton2ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 139));
        jLabel6.setText("Days :");

        daysTextField.setBackground(new java.awt.Color(255, 254, 238));
        daysTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        daysTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 139));
        jLabel7.setText("Ward Number :");

        wardNumberTextField.setBackground(new java.awt.Color(255, 254, 238));
        wardNumberTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        wardNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardNumberTextFieldActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(0, 0, 139));
        jLabel15.setText("Outcome :");

        majorComplicationTextField.setBackground(new java.awt.Color(255, 254, 238));
        majorComplicationTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        majorComplicationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majorComplicationTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 0, 139));
        jLabel8.setText("Results :");

        resultsTextField.setBackground(new java.awt.Color(255, 254, 238));
        resultsTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        resultsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(medicineNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(providerTextField)
                    .addComponent(dateTextField))
                .addGap(30, 30, 30)
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound4Layout.createSequentialGroup()
                        .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound4Layout.createSequentialGroup()
                        .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(durationTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(problemTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(46, 46, 46)
                        .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(wardedRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wardedRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(outcomeTextField)
                        .addComponent(wardNumberTextField)
                        .addComponent(daysTextField)
                        .addComponent(majorComplicationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resultsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(providerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(medicineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(durationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRound4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRound4Layout.createSequentialGroup()
                                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound4Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15))
                                    .addGroup(panelRound4Layout.createSequentialGroup()
                                        .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(problemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(wardedRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wardedRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34))
                            .addGroup(panelRound4Layout.createSequentialGroup()
                                .addComponent(daysTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(wardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outcomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(majorComplicationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))))
                        .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(resultsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 1090, 180));

        panelRound1.setBackground(new java.awt.Color(211, 221, 255));

        reactionTextField.setBackground(new java.awt.Color(255, 254, 238));
        reactionTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        reactionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reactionTextFieldActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(0, 0, 139));
        jLabel16.setText("Reaction :");

        jLabel12.setForeground(new java.awt.Color(0, 0, 139));
        jLabel12.setText("Please state the allergies : ");

        allergyTextField.setBackground(new java.awt.Color(255, 254, 238));
        allergyTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        allergyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allergyTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 139));
        jLabel5.setForeground(new java.awt.Color(0, 0, 139));
        jLabel5.setText("Does the patient have any allergies :");

        buttonGroup2.add(allergiesRadioButton3);
        allergiesRadioButton3.setForeground(new java.awt.Color(0, 0, 139));
        allergiesRadioButton3.setText("YES");
        allergiesRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allergiesRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(allergiesRadioButton4);
        allergiesRadioButton4.setForeground(new java.awt.Color(0, 0, 139));
        allergiesRadioButton4.setText("NO");
        allergiesRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allergiesRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reactionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allergiesRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergiesRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergiesRadioButton3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(allergiesRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(allergyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reactionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18))
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 310, -1));

        panelRound2.setBackground(new java.awt.Color(211, 221, 255));

        nameOfVaccineTextField.setBackground(new java.awt.Color(255, 254, 238));
        nameOfVaccineTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        nameOfVaccineTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameOfVaccineTextFieldActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(0, 0, 139));
        jLabel17.setText("Please state the name for each vaccine :");

        jLabel19.setForeground(new java.awt.Color(0, 0, 139));
        jLabel19.setText("Has the patient ever been vaccinated in the past :");

        buttonGroup3.add(vaccineRadioButton5);
        vaccineRadioButton5.setForeground(new java.awt.Color(0, 0, 139));
        vaccineRadioButton5.setText("YES");
        vaccineRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroup3.add(vaccineRadioButton6);
        vaccineRadioButton6.setForeground(new java.awt.Color(0, 0, 139));
        vaccineRadioButton6.setText("NO");
        vaccineRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineRadioButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameOfVaccineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaccineRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaccineRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(155, 155, 155))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vaccineRadioButton5)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(vaccineRadioButton6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameOfVaccineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 380, 130));

        panelRound3.setBackground(new java.awt.Color(211, 221, 255));

        diseaseTextField.setBackground(new java.awt.Color(255, 254, 238));
        diseaseTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        diseaseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diseaseTextFieldActionPerformed(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(0, 0, 139));
        jLabel18.setText("Name of the disease :");

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diseaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diseaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 200, 130));

        customPanelButton1.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton1.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton1.setText("A D D");
        customPanelButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customPanelButton1.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton1.setRadius(20);
        customPanelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(customPanelButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 370, 150, 30));

        customPanelButton2.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton2.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton2.setText("E D I T");
        customPanelButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customPanelButton2.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton2.setRadius(20);
        customPanelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(customPanelButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 410, 150, 30));

        customPanelButton3.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton3.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton3.setText("R E F R E S H ");
        customPanelButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customPanelButton3.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton3.setRadius(20);
        customPanelButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(customPanelButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 450, 150, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 1090, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/medicalHistoryIcon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1040, 110));

        customPanelButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139), 2));
        customPanelButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/homeIcon.png"))); // NOI18N
        customPanelButton4.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(customPanelButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, -1, -1));

        customPanelButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139), 2));
        customPanelButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/infoIcon.png"))); // NOI18N
        customPanelButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(customPanelButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 90, -1, -1));

        customPanelButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139), 2));
        customPanelButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/logOffIcon.png"))); // NOI18N
        customPanelButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(customPanelButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 254, 238));
        jPanel2.setMaximumSize(new java.awt.Dimension(1200, 900));
        jPanel2.setMinimumSize(new java.awt.Dimension(1200, 900));
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void timeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTextFieldActionPerformed

    private void providerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_providerTextFieldActionPerformed

    private void medicineNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineNameTextFieldActionPerformed

    private void resultsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultsTextFieldActionPerformed

    private void durationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationTextFieldActionPerformed

    private void problemTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_problemTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_problemTextFieldActionPerformed

    private void outcomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outcomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outcomeTextFieldActionPerformed

    private void majorComplicationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majorComplicationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_majorComplicationTextFieldActionPerformed

    private void wardedRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardedRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wardedRadioButton1ActionPerformed

    private void daysTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daysTextFieldActionPerformed

    private void wardNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wardNumberTextFieldActionPerformed

    private void wardedRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardedRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wardedRadioButton2ActionPerformed

    private void allergiesRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allergiesRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allergiesRadioButton3ActionPerformed

    private void allergiesRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allergiesRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allergiesRadioButton4ActionPerformed

    private void reactionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reactionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reactionTextFieldActionPerformed

    private void allergyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allergyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allergyTextFieldActionPerformed

    private void vaccineRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccineRadioButton5ActionPerformed

    private void vaccineRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccineRadioButton6ActionPerformed

    private void nameOfVaccineTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameOfVaccineTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameOfVaccineTextFieldActionPerformed

    private void diseaseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diseaseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diseaseTextFieldActionPerformed

    private void customPanelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton1ActionPerformed
        //Getting all the values to be added from the textfields
        int value1 = 001;
        String value2 = dateTextField.getText(); 
        String value3= timeTextField.getText();
        boolean value4;
        
        if (wardedRadioButton1.isSelected()) {
            value4 = true;
        } 
        
        else if (wardedRadioButton2.isSelected()) {
            value4 = false;
        } 
        else {
            value4 = false; 
        }
        
        int value5 = Integer.parseInt(daysTextField.getText());
        int value6 = Integer.parseInt(wardNumberTextField.getText());
        String value7 = providerTextField.getText();
        String value8 = problemTextField.getText();
        String value9 = majorComplicationTextField.getText();
        String value10 = durationTextField.getText();
        String value11 = resultsTextField.getText();
        String value12 = outcomeTextField.getText();
        String value13 = medicineNameTextField.getText();
        boolean value14;
        
        if (allergiesRadioButton3.isSelected()) {
            value14 = true;
        } 
        else if (allergiesRadioButton4.isSelected()) {
            value14 = false;
        } 
        else {
            value14 = false; 
        }
        
        String value15 = allergyTextField.getText();
        String value16 = reactionTextField.getText();
        boolean value17;
        
        if (vaccineRadioButton5.isSelected()) {
            value17 = true;
        } 
        else if (vaccineRadioButton6.isSelected()) {
            value17 = false;
        } 
        else {
            value17 = false; 
        }
        
        String value18 = nameOfVaccineTextField.getText();
        String value19 = diseaseTextField.getText();
        
        //Passing those value into the constructor of the respective classes
    
        MedicalForm medicalForm1 = new MedicalForm(value1,value2,value3,value4,value5,value6,value7,value8,value9,value10,value11,value12,value13);

        Allergy allergy1 = new Allergy(value1,value2,value3,value4,value5,value6,value7,value8,value9,value10,value11,value12,value13,value14,value15,value16);
        
        Disease disease1 = new Disease(value1,value2,value3,value4,value5,value6,value7,value8,value9,value10,value11,value12,value13,value19);

        Vaccine vaccine1 = new Vaccine(value1,value2,value3,value4,value5,value6,value7,value8,value9,value10,value11,value12,value13,value17,value18);

        /*Using getters to get the values from the object and concatinating them into one vairable to be added as a new line 
        at the end of the textfile writing the line to the end of the textfile
        */
        
        String adding = "\n" + medicalForm1.getPatientID() + "," + medicalForm1.getDate() + "," + medicalForm1.getTime() + "," + medicalForm1.getWarded() + "," + medicalForm1.getWardNumber() + "," + medicalForm1.getDays() + "," + 
                         medicalForm1.getProvider() + "," + medicalForm1.getProblem() + "," + medicalForm1.getMajorComplication() + "," + medicalForm1.getMedicineName() + "," + medicalForm1.getDuration() + "," + 
                         medicalForm1.getOutcome() + "," + medicalForm1.getResults() + "," + allergy1.getStatus() + "," + allergy1.getNameOfAllergies() + "," + allergy1.getReaction() + "," + 
                         vaccine1.getVaccinated() + "," + vaccine1.getNameOfVaccine() + "," + disease1.getNameOfDisease();
        
        String filePath = "C:\\Users\\abdul\\Documents\\NetBeansProjects\\PatientMedicalHistory\\patientMedicalHistory.txt"; 
        
        try {
//          Writing the line of values to the end of the textfile 
            Files.write(Paths.get(filePath), adding.getBytes(), StandardOpenOption.APPEND);
            
        } 
        
        catch (IOException ex) {
           ex.printStackTrace();
        }
    }//GEN-LAST:event_customPanelButton1ActionPerformed

    private void customPanelButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton2ActionPerformed
String filePath = "C:\\Users\\abdul\\Documents\\NetBeansProjects\\PatientMedicalHistory\\patientMedicalHistory.txt"; 
        
        //Intiliazing a file object 
        File file = new File(filePath); 
        
       try{
           //Intiliazing a FileWriter and BufferedWriter
           FileWriter fw = new FileWriter(file); 
            BufferedWriter bw = new BufferedWriter(fw); 
           //Writing the first line in the textfile which will be used as column headers in the table
           bw.write("patientID,date,time,warded,days,wardNumber,provider,problem,majorComplication,medicineName,duration,outcome,results,status,nameOfAllergies,reaction,vaccinated,nameOfVaccine,nameOfDisease");
           //jumping to next line to start entering the data
           bw.newLine();
           
           //Using two for loops to traverse through the rows in each column to read the data and store it into the textfile
           for(int i = 0; i < jTable1.getRowCount(); i++){
               for(int j = 0; j < jTable1.getColumnCount(); j++){
                   //Writing the data at the current column and row to the textfile and then adding a "," to make it a csv file
                  Object value = jTable1.getValueAt(i,j);
                   if (value != null){
                       bw.write(value.toString());
                   
                   
               }
               bw.write(",");
               
           }
               //Creating new line to for next loop iteration 
               bw.newLine();
       }
           //Closing the BufferedWriter and FileWriter
        bw.close();
        fw.close();
        
       }
        catch(IOException ex){
            System.out.println("Errror");
        }

    }//GEN-LAST:event_customPanelButton2ActionPerformed

    private void customPanelButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton3ActionPerformed
    String filePath = "C:\\Users\\abdul\\Documents\\NetBeansProjects\\PatientMedicalHistory\\patientMedicalHistory.txt"; 
   
    //Intiliazing a file object
    File file = new File(filePath); 


        try {
            //Initializing a BufferedReader to read file
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim(); 
            /*
            Splitting the values of the first line by a coma
            Storing those values line
            */
            String[] columnsName = firstLine.split(",");
            
            //Getting the default table model to identify columns and rows
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); 
            
            //setting the array values as column identifiers
            model.setColumnIdentifiers(columnsName);
            
            //setting row count as 0, so old values are not repeated again after each refresh
            model.setRowCount(0);
            Object[] tableLines = br.lines().toArray(); 
            
            /*
            Using a for loop to go through each value in the textfile
            All characters after a coma are read as a single word
            The word is then pushed into the table at the current index of row and column in the for loop
            */
            
            for (Object tableLine : tableLines) {
                String line = tableLine.toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);
             }
            
        } 
        
        catch (IOException ex) {
            Logger.getLogger(MedicalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_customPanelButton3ActionPerformed

    private void customPanelButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton4ActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_customPanelButton4ActionPerformed

    private void customPanelButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton5ActionPerformed
        new MedicalHistoryForm().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_customPanelButton5ActionPerformed

    private void customPanelButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton6ActionPerformed
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customPanelButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicalHistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicalHistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicalHistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicalHistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
            new MedicalHistoryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allergiesRadioButton3;
    private javax.swing.JRadioButton allergiesRadioButton4;
    private javax.swing.JTextField allergyTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private emr.system.customComponents.CustomPanelButton customPanelButton1;
    private emr.system.customComponents.CustomPanelButton customPanelButton2;
    private emr.system.customComponents.CustomPanelButton customPanelButton3;
    private emr.system.customComponents.CustomPanelButton customPanelButton4;
    private emr.system.customComponents.CustomPanelButton customPanelButton5;
    private emr.system.customComponents.CustomPanelButton customPanelButton6;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField daysTextField;
    private javax.swing.JTextField diseaseTextField;
    private javax.swing.JTextField durationTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private emr.system.customComponents.CustomTable jTable1;
    private javax.swing.JTextField majorComplicationTextField;
    private javax.swing.JTextField medicineNameTextField;
    private javax.swing.JTextField nameOfVaccineTextField;
    private javax.swing.JTextField outcomeTextField;
    private emr.system.PanelRound panelRound1;
    private emr.system.PanelRound panelRound2;
    private emr.system.PanelRound panelRound3;
    private emr.system.PanelRound panelRound4;
    private javax.swing.JTextField problemTextField;
    private javax.swing.JTextField providerTextField;
    private javax.swing.JTextField reactionTextField;
    private javax.swing.JTextField resultsTextField;
    private javax.swing.JTextField timeTextField;
    private javax.swing.JRadioButton vaccineRadioButton5;
    private javax.swing.JRadioButton vaccineRadioButton6;
    private javax.swing.JTextField wardNumberTextField;
    private javax.swing.JRadioButton wardedRadioButton1;
    private javax.swing.JRadioButton wardedRadioButton2;
    // End of variables declaration//GEN-END:variables
}
