/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emr.system;

import emr.system.classes.EmergencyContact;
import emr.system.classes.PatientInfo;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lxhui
 */
public class PatientInfoForm extends javax.swing.JFrame {

    /**
     * Creates new form PatientInfo
     */
    public PatientInfoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientInfoTable = new emr.system.customComponents.CustomTable();
        panelRound1 = new emr.system.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        iCNoTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pNameTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        genderTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        doBTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        marritalStatTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mobileTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        emailTextField1 = new javax.swing.JTextField();
        allergyTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        homeTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextArea1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        weightTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        heightTextField1 = new javax.swing.JTextField();
        bloodTypeTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ethnicityTextField1 = new javax.swing.JTextField();
        panelRound2 = new emr.system.PanelRound();
        jLabel19 = new javax.swing.JLabel();
        emergContactMobileTextField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        emergContactTextField1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        emergContactRelationshipTextField1 = new javax.swing.JTextField();
        customButton1 = new emr.system.customComponents.CustomButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        emergencyContactInfoTable = new emr.system.customComponents.CustomTable();
        jLabel22 = new javax.swing.JLabel();
        customButton2 = new emr.system.customComponents.CustomButton();
        customButton3 = new emr.system.customComponents.CustomButton();
        customButton4 = new emr.system.customComponents.CustomButton();
        customButton5 = new emr.system.customComponents.CustomButton();
        customPanelButton4 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton5 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton6 = new emr.system.customComponents.CustomPanelButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 254, 238));
        setMaximumSize(new java.awt.Dimension(1300, 800));
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setPreferredSize(new java.awt.Dimension(1300, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 254, 238));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 139));
        jLabel1.setText("Patient Admission Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 139));
        jLabel2.setText("Patient Information");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        patientInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(patientInfoTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 1240, 60));

        panelRound1.setBackground(new java.awt.Color(211, 221, 255));
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(0, 0, 139));
        jLabel3.setText("Patient Name: ");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        iCNoTextField1.setBackground(new java.awt.Color(255, 254, 238));
        iCNoTextField1.setToolTipText("");
        iCNoTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        iCNoTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCNoTextField1ActionPerformed(evt);
            }
        });
        panelRound1.add(iCNoTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 240, 20));

        jLabel4.setForeground(new java.awt.Color(0, 0, 139));
        jLabel4.setText("IC/Passport Number: ");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        pNameTextField1.setBackground(new java.awt.Color(255, 254, 238));
        pNameTextField1.setToolTipText("");
        pNameTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        pNameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameTextField1ActionPerformed(evt);
            }
        });
        panelRound1.add(pNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 240, 20));

        jLabel6.setForeground(new java.awt.Color(0, 0, 139));
        jLabel6.setText("Gender: ");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, 20));

        genderTextField1.setBackground(new java.awt.Color(255, 254, 238));
        genderTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        genderTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTextField1ActionPerformed(evt);
            }
        });
        panelRound1.add(genderTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 190, 20));

        jLabel7.setForeground(new java.awt.Color(0, 0, 139));
        jLabel7.setText("Date of Birth: ");
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, 20));

        doBTextField1.setBackground(new java.awt.Color(255, 254, 238));
        doBTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        doBTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doBTextField1ActionPerformed(evt);
            }
        });
        panelRound1.add(doBTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 240, 20));

        jLabel9.setForeground(new java.awt.Color(0, 0, 139));
        jLabel9.setText("Marrital Status: ");
        panelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 20));

        marritalStatTextField1.setBackground(new java.awt.Color(255, 254, 238));
        marritalStatTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        marritalStatTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marritalStatTextField1ActionPerformed(evt);
            }
        });
        panelRound1.add(marritalStatTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 190, 20));

        jLabel10.setForeground(new java.awt.Color(0, 0, 139));
        jLabel10.setText("Mobile Phone: ");
        panelRound1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        mobileTextField1.setBackground(new java.awt.Color(255, 254, 238));
        mobileTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        panelRound1.add(mobileTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 240, 20));

        jLabel11.setForeground(new java.awt.Color(0, 0, 139));
        jLabel11.setText("Home Phone: ");
        panelRound1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 139));
        jLabel12.setText("Email: ");
        panelRound1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        emailTextField1.setBackground(new java.awt.Color(255, 254, 238));
        emailTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        panelRound1.add(emailTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 20));

        allergyTextField1.setBackground(new java.awt.Color(255, 254, 238));
        allergyTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        panelRound1.add(allergyTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 190, 70));

        jLabel14.setForeground(new java.awt.Color(0, 0, 139));
        jLabel14.setText("Address: ");
        panelRound1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        homeTextField1.setBackground(new java.awt.Color(255, 254, 238));
        homeTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        panelRound1.add(homeTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 240, 20));

        addressTextArea1.setBackground(new java.awt.Color(255, 254, 238));
        addressTextArea1.setColumns(20);
        addressTextArea1.setLineWrap(true);
        addressTextArea1.setRows(2);
        addressTextArea1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        jScrollPane1.setViewportView(addressTextArea1);

        panelRound1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 780, 30));

        jLabel15.setForeground(new java.awt.Color(0, 0, 139));
        jLabel15.setText("Allergies: ");
        panelRound1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 20));

        jLabel16.setForeground(new java.awt.Color(0, 0, 139));
        jLabel16.setText("Height: ");
        panelRound1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, 20));

        weightTextField1.setBackground(new java.awt.Color(255, 254, 238));
        weightTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        panelRound1.add(weightTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 190, 20));

        jLabel17.setForeground(new java.awt.Color(0, 0, 139));
        jLabel17.setText("Weight: ");
        panelRound1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, 20));

        heightTextField1.setBackground(new java.awt.Color(255, 254, 238));
        heightTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        heightTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTextField1ActionPerformed(evt);
            }
        });
        panelRound1.add(heightTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 190, 20));

        bloodTypeTextField1.setBackground(new java.awt.Color(255, 254, 238));
        bloodTypeTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        panelRound1.add(bloodTypeTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 200, 20));

        jLabel8.setForeground(new java.awt.Color(0, 0, 139));
        jLabel8.setText("Blood Type: ");
        panelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, 20));

        jLabel13.setForeground(new java.awt.Color(0, 0, 139));
        jLabel13.setText("Ethnicity: ");
        panelRound1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 20));

        ethnicityTextField1.setBackground(new java.awt.Color(255, 254, 238));
        ethnicityTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        panelRound1.add(ethnicityTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 190, 20));

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 820, 410));

        panelRound2.setBackground(new java.awt.Color(211, 221, 255));
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setForeground(new java.awt.Color(0, 0, 139));
        jLabel19.setText("Relationship: ");
        panelRound2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        emergContactMobileTextField1.setBackground(new java.awt.Color(255, 254, 238));
        emergContactMobileTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        panelRound2.add(emergContactMobileTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 177, 140, 20));

        jLabel20.setForeground(new java.awt.Color(0, 0, 139));
        jLabel20.setText("Mobile Phone: ");
        panelRound2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        emergContactTextField1.setBackground(new java.awt.Color(255, 254, 238));
        emergContactTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        panelRound2.add(emergContactTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 20));

        jLabel21.setForeground(new java.awt.Color(0, 0, 139));
        jLabel21.setText("Name: ");
        panelRound2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        emergContactRelationshipTextField1.setBackground(new java.awt.Color(255, 254, 238));
        emergContactRelationshipTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        emergContactRelationshipTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergContactRelationshipTextField1ActionPerformed(evt);
            }
        });
        panelRound2.add(emergContactRelationshipTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 20));

        customButton1.setBackground(new java.awt.Color(255, 254, 238));
        customButton1.setForeground(new java.awt.Color(0, 0, 139));
        customButton1.setText("A D D");
        customButton1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        customButton1.setOutlineColor(new java.awt.Color(0, 0, 139));
        customButton1.setRadius(25);
        customButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton1ActionPerformed(evt);
            }
        });
        panelRound2.add(customButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 160, 100));

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 180, 410));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 139));
        jLabel18.setText("Emergency Contact");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, -1, 20));

        emergencyContactInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(emergencyContactInfoTable);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 1240, 70));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 139));
        jLabel22.setText("Emergency Contact Information ");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, 20));

        customButton2.setBackground(new java.awt.Color(255, 254, 238));
        customButton2.setForeground(new java.awt.Color(0, 0, 139));
        customButton2.setText("R E F R E S H");
        customButton2.setOutlineColor(new java.awt.Color(0, 0, 139));
        customButton2.setRadius(25);
        customButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(customButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 550, -1, -1));

        customButton3.setBackground(new java.awt.Color(255, 254, 238));
        customButton3.setForeground(new java.awt.Color(0, 0, 139));
        customButton3.setText("R E F R E S H");
        customButton3.setOutlineColor(new java.awt.Color(0, 0, 139));
        customButton3.setRadius(25);
        customButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(customButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 650, -1, -1));

        customButton4.setBackground(new java.awt.Color(255, 254, 238));
        customButton4.setForeground(new java.awt.Color(0, 0, 139));
        customButton4.setText("E D I T");
        customButton4.setOutlineColor(new java.awt.Color(0, 0, 139));
        customButton4.setRadius(25);
        customButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(customButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 650, -1, -1));

        customButton5.setBackground(new java.awt.Color(255, 254, 238));
        customButton5.setForeground(new java.awt.Color(0, 0, 139));
        customButton5.setText("E D I T");
        customButton5.setOutlineColor(new java.awt.Color(0, 0, 139));
        customButton5.setRadius(25);
        customButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(customButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 550, -1, -1));

        customPanelButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139), 2));
        customPanelButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/homeIcon.png"))); // NOI18N
        customPanelButton4.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(customPanelButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 20, -1, -1));

        customPanelButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139), 2));
        customPanelButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/infoIcon.png"))); // NOI18N
        customPanelButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(customPanelButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 90, -1, -1));

        customPanelButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139), 2));
        customPanelButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/logOffIcon.png"))); // NOI18N
        customPanelButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(customPanelButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 160, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/patientInformationIcon.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1160, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 920));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void heightTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightTextField1ActionPerformed

    private void doBTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doBTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doBTextField1ActionPerformed

    private void genderTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTextField1ActionPerformed

    private void pNameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNameTextField1ActionPerformed

    private void iCNoTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCNoTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iCNoTextField1ActionPerformed

    private void emergContactRelationshipTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergContactRelationshipTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergContactRelationshipTextField1ActionPerformed

    private void customButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton1ActionPerformed
         // Getting all the values to be added from the textfields
        String value1 = pNameTextField1.getText();
        String value2 = iCNoTextField1.getText();
        int value3 = 001; 
        String value4 = genderTextField1.getText();
        String value5 = doBTextField1.getText();
        String value6 = marritalStatTextField1.getText();
        String value7 = bloodTypeTextField1.getText();
        String value8 = allergyTextField1.getText();
        String value9 = heightTextField1.getText();
        String value10 = weightTextField1.getText();
        String value11 = ethnicityTextField1.getText();
        int value12 = Integer.parseInt(mobileTextField1.getText());
        int value13 = Integer.parseInt(homeTextField1.getText());
        String value14 = emailTextField1.getText();
        String value15 = addressTextArea1.getText();
        String value16 = emergContactTextField1.getText();
        String value17 = emergContactRelationshipTextField1.getText();
        int value18 = Integer.parseInt(emergContactMobileTextField1.getText());

        //passing those values into the constructor of the class
        
        PatientInfo patientInfo1 = new PatientInfo(value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15);
        EmergencyContact emergencyContact1 = new EmergencyContact(value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, value17, value18);

        //Using getters to get the values from the object and concatinating them into one variable to be added a new line
        //at the end of the textfile writing the line to the end of the textfile
        
        String adding = "\n" + patientInfo1.getPatientName() + "," + patientInfo1.getIC_passportNo() + "," + patientInfo1.getPatientID() + "," + patientInfo1.getGender() + "," + patientInfo1.getDoB() + "," + patientInfo1.getMarritalStatus() + "," + patientInfo1.getBloodGroup() + "," + patientInfo1.getAllergy() + "," + patientInfo1.getHeight() + "," + patientInfo1.getWeight() + "," + patientInfo1.getEthnicity() + "," + patientInfo1.getMobilePhone() + "," + patientInfo1.getHomePhone() + "," + patientInfo1.getEmail() + "," + patientInfo1.getAddress() + ","; 
        String addingEmergencyContact = "\n" + emergencyContact1.getEmergencyContactName() + "," + emergencyContact1.getRelationshipToPatient() + "," + emergencyContact1.getEmergencyContactMobile();
       
        String filePath = "C:\\Users\\Rayyan\\Desktop\\PatientInfo.txt";
        String emergencyContactFilePath = "C:\\Users\\Rayyan\\Desktop.EmergencyContactInfo.txt"; 
        try {
            Files.write(Paths.get(filePath), adding.getBytes(), StandardOpenOption.APPEND);
            Files.write(Paths.get(filePath), addingEmergencyContact.getBytes(), StandardOpenOption.APPEND);

        } catch (IOException ex) {
            ex.printStackTrace();
        }        
    }//GEN-LAST:event_customButton1ActionPerformed

    private void customButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton2ActionPerformed
 String filePath = "C:\\Users\\lxhui\\Desktop\\PatientInfo.txt";
        //Initializing a file object
        File file = new File(filePath); 

        try {
            //Initializing a BufferredReader to read file
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim(); 
            /*
            Splitting the values of the first line by a coma
            Storing those values line 
            */
            String[] columnsName = firstLine.split(",");
            
            //Getting the default table model to identify columns and rows
            
            DefaultTableModel model = (DefaultTableModel)patientInfoTable.getModel(); 
            
            //Setting the array values as column identifiers 
            model.setColumnIdentifiers(columnsName);
            
            //Setting row count as 0, so old values are not repeated again after each refresh
            model.setRowCount(0);
            Object[] tableLines = br.lines().toArray(); 
            
            /*
            Using a for loop to go through each value in the textfile
            All characters after a coma are read as a single word
            The word is then pushed into the table at the current index of row and column in the for loop
            */
            for (int i = 0; i < tableLines.length; i++){
            String line= tableLines[i].toString().trim();
            String[] dataRow = line.split(","); 
            model.addRow(dataRow);
            
                   
            
            }
            // TODO add your handling code here:
        } catch (Exception ex) {
            System.out.println("Error");
        }
             
                                                  
    }//GEN-LAST:event_customButton2ActionPerformed

    private void customButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton3ActionPerformed
        String filePath = "C:\\Users\\Rayyan\\Desktop\\EmergencyContactInfo.txt";
        //Initializing a file object
        File file = new File(filePath); 

        try {
            //Initializing a BufferredReader to read file
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim(); 
            /*
            Splitting the values of the first line by a coma
            Storing those values line 
            */
            String[] columnsName = firstLine.split(",");
            
            //Getting the default table model to identify columns and rows
            
            DefaultTableModel model = (DefaultTableModel)emergencyContactInfoTable.getModel(); 
            
            //Setting the array values as column identifiers 
            model.setColumnIdentifiers(columnsName);
            
            //Setting row count as 0, so old values are not repeated again after each refresh
            model.setRowCount(0);
            Object[] tableLines = br.lines().toArray(); 
            
            /*
            Using a for loop to go through each value in the textfile
            All characters after a coma are read as a single word
            The word is then pushed into the table at the current index of row and column in the for loop
            */
            for (int i = 0; i < tableLines.length; i++){
            String line= tableLines[i].toString().trim();
            String[] dataRow = line.split(","); 
            model.addRow(dataRow);
            
                   
            
            }
            // TODO add your handling code here:
        } catch (Exception ex) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_customButton3ActionPerformed

    private void customButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton4ActionPerformed
 String filePath = "C:\\Users\\lxhui\\Desktop\\PatientInfo.txt"; 
        
        //Initializing a file object
        File file = new File(filePath); 
        
        try{
            //Initializing a fileWriter and BufferWriter 
        FileWriter fw = new FileWriter(file); 
        BufferedWriter bw = new BufferedWriter(fw); 
        
        //Writing the first line in the textfile which will be used as column headers in the table 
        bw.write("Emergency Contact Name, Relationship to patient, Mobile Number ");
        
        //Jumping to the next line to start entering the data
        bw.newLine();
        
        //Using two loops to traverse through the rows in each column to read the data and store it into the textfile 
        for(int i =0; i < emergencyContactInfoTable.getRowCount(); i++){
            for(int j = 0; j < emergencyContactInfoTable.getColumnCount(); j++){
                //Writing the data at the current column and row to the textfile and then adding a "," to make it a csv file
                Object value = emergencyContactInfoTable.getValueAt(i, j);
                if(value != null) {
                    bw.write(value.toString());
                }
                bw.write(",");
            }
            //Creating a new line for next loop iteration
            bw.newLine();
            
        }
        //Closing the BufferWriter and FileWriter
        bw.close(); 
        fw.close();
        
        
        }
        catch(IOException ex){
            System.out.println("Error");
        }
    }//GEN-LAST:event_customButton4ActionPerformed

    private void customButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton5ActionPerformed
 String filePath = "C:\\Users\\lxhui\\Desktop\\PatientInfo.txt"; 
        
        //Initializing a file object
        File file = new File(filePath); 
        
        try{
            //Initializing a fileWriter and BufferWriter 
        FileWriter fw = new FileWriter(file); 
        BufferedWriter bw = new BufferedWriter(fw); 
        
        //Writing the first line in the textfile which will be used as column headers in the table 
        bw.write("Patient Name, IC Number, Patient ID, Gender, Date of Birth, Marrital Status, Blood Group, Allergy, Height, Weight, Ethnicity, Mobile Phone, Home Phone, Email, Address");
        
        //Jumping to the next line to start entering the data
        bw.newLine();
        
        //Using two loops to traverse through the rows in each column to read the data and store it into the textfile 
        for(int i =0; i < patientInfoTable.getRowCount(); i++){
            for(int j = 0; j < patientInfoTable.getColumnCount(); j++){
                //Writing the data at the current column and row to the textfile and then adding a "," to make it a csv file
                Object value = patientInfoTable.getValueAt(i, j);
                if(value != null) {
                    bw.write(value.toString());
                }
                bw.write(",");
            }
            //Creating a new line for next loop iteration
            bw.newLine();
            
        }
        //Closing the BufferWriter and FileWriter
        bw.close(); 
        fw.close();
        
        
        }
        catch(IOException ex){
            System.out.println("Error");
        }
    }//GEN-LAST:event_customButton5ActionPerformed

    private void marritalStatTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marritalStatTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marritalStatTextField1ActionPerformed

    private void customPanelButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton4ActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customPanelButton4ActionPerformed

    private void customPanelButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton5ActionPerformed
        new MedicalHistoryForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customPanelButton5ActionPerformed

    private void customPanelButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton6ActionPerformed
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customPanelButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientInfoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressTextArea1;
    private javax.swing.JTextField allergyTextField1;
    private javax.swing.JTextField bloodTypeTextField1;
    private emr.system.customComponents.CustomButton customButton1;
    private emr.system.customComponents.CustomButton customButton2;
    private emr.system.customComponents.CustomButton customButton3;
    private emr.system.customComponents.CustomButton customButton4;
    private emr.system.customComponents.CustomButton customButton5;
    private emr.system.customComponents.CustomPanelButton customPanelButton4;
    private emr.system.customComponents.CustomPanelButton customPanelButton5;
    private emr.system.customComponents.CustomPanelButton customPanelButton6;
    private javax.swing.JTextField doBTextField1;
    private javax.swing.JTextField emailTextField1;
    private javax.swing.JTextField emergContactMobileTextField1;
    private javax.swing.JTextField emergContactRelationshipTextField1;
    private javax.swing.JTextField emergContactTextField1;
    private emr.system.customComponents.CustomTable emergencyContactInfoTable;
    private javax.swing.JTextField ethnicityTextField1;
    private javax.swing.JTextField genderTextField1;
    private javax.swing.JTextField heightTextField1;
    private javax.swing.JTextField homeTextField1;
    private javax.swing.JTextField iCNoTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField marritalStatTextField1;
    private javax.swing.JTextField mobileTextField1;
    private javax.swing.JTextField pNameTextField1;
    private emr.system.PanelRound panelRound1;
    private emr.system.PanelRound panelRound2;
    private emr.system.customComponents.CustomTable patientInfoTable;
    private javax.swing.JTextField weightTextField1;
    // End of variables declaration//GEN-END:variables
}
