/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emr.system;

import emr.system.classes.Liquid;
import emr.system.classes.Surgical;
import emr.system.classes.Tablet;
import emr.system.classes.Diagnostic;
import emr.system.classes.Medicine;
import emr.system.classes.Procedure;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SARAVANAPRIYA
 */
public class ProcedureAndMedicineForm extends javax.swing.JFrame {

    /**
     * Creates new form ProcedureandMedicine
     */
    public ProcedureAndMedicineForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelRound1 = new emr.system.PanelRound();
        procedureID = new javax.swing.JLabel();
        procedureIDTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        timeTextField = new javax.swing.JTextField();
        procedureType = new javax.swing.JLabel();
        procedureDescription = new javax.swing.JLabel();
        procedureDescriptionTextField = new javax.swing.JTextField();
        surgeon = new javax.swing.JLabel();
        surgeonTextField = new javax.swing.JTextField();
        specialist = new javax.swing.JLabel();
        specialistTextField = new javax.swing.JTextField();
        patientID = new javax.swing.JLabel();
        patientIDTextField = new javax.swing.JTextField();
        diagnosticTypeTextField = new javax.swing.JTextField();
        diagnosticType = new javax.swing.JLabel();
        procedureTypeTextField = new javax.swing.JTextField();
        panelRound2 = new emr.system.PanelRound();
        medicineID = new javax.swing.JLabel();
        medicineIDTextField = new javax.swing.JTextField();
        medicineName = new javax.swing.JLabel();
        medicineNameTextField = new javax.swing.JTextField();
        medicineDescription = new javax.swing.JLabel();
        medicineDescriptionTextField = new javax.swing.JTextField();
        amount = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        frequency = new javax.swing.JLabel();
        frequencyTextField = new javax.swing.JTextField();
        providerTextField = new javax.swing.JTextField();
        provider = new javax.swing.JLabel();
        tabletDosage = new javax.swing.JLabel();
        tabletDosageTextField = new javax.swing.JTextField();
        liquidVolume = new javax.swing.JLabel();
        liquidVolumeTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new emr.system.customComponents.CustomTable();
        customPanelButton1 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton2 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton3 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton6 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton4 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton5 = new emr.system.customComponents.CustomPanelButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 254, 238));
        jPanel2.setMaximumSize(new java.awt.Dimension(1200, 900));
        jPanel2.setMinimumSize(new java.awt.Dimension(1200, 900));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 900));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(211, 221, 255));
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        procedureID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        procedureID.setForeground(new java.awt.Color(0, 0, 139));
        procedureID.setText("Procedure ID:");
        panelRound1.add(procedureID, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 39, -1, -1));

        procedureIDTextField.setBackground(new java.awt.Color(255, 254, 238));
        procedureIDTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        procedureIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procedureIDTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(procedureIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 39, 100, -1));

        dateTextField.setBackground(new java.awt.Color(255, 254, 238));
        dateTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(dateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 74, 100, -1));

        date.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        date.setForeground(new java.awt.Color(0, 0, 139));
        date.setText("Date:");
        panelRound1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 74, -1, -1));

        time.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        time.setForeground(new java.awt.Color(0, 0, 139));
        time.setText("Time:");
        panelRound1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 109, -1, -1));

        timeTextField.setBackground(new java.awt.Color(255, 254, 238));
        timeTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        timeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(timeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 109, 100, -1));

        procedureType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        procedureType.setForeground(new java.awt.Color(0, 0, 139));
        procedureType.setText("Procedure Type:");
        panelRound1.add(procedureType, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 144, -1, -1));

        procedureDescription.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        procedureDescription.setForeground(new java.awt.Color(0, 0, 139));
        procedureDescription.setText("Procedure Description:");
        panelRound1.add(procedureDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        procedureDescriptionTextField.setBackground(new java.awt.Color(255, 254, 238));
        procedureDescriptionTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        procedureDescriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procedureDescriptionTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(procedureDescriptionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 130, 60));

        surgeon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        surgeon.setForeground(new java.awt.Color(0, 0, 139));
        surgeon.setText("Surgeon:");
        panelRound1.add(surgeon, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 187, -1, -1));

        surgeonTextField.setBackground(new java.awt.Color(255, 254, 238));
        surgeonTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        surgeonTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surgeonTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(surgeonTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 187, 100, -1));

        specialist.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        specialist.setForeground(new java.awt.Color(0, 0, 139));
        specialist.setText("Specialist:");
        panelRound1.add(specialist, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 237, -1, -1));

        specialistTextField.setBackground(new java.awt.Color(255, 254, 238));
        specialistTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        specialistTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialistTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(specialistTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 237, 100, -1));

        patientID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        patientID.setForeground(new java.awt.Color(0, 0, 139));
        patientID.setText("PatientID:");
        panelRound1.add(patientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 288, -1, -1));

        patientIDTextField.setBackground(new java.awt.Color(255, 254, 238));
        patientIDTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        patientIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIDTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(patientIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 288, 100, -1));

        diagnosticTypeTextField.setBackground(new java.awt.Color(255, 254, 238));
        diagnosticTypeTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        panelRound1.add(diagnosticTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 332, 100, -1));

        diagnosticType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diagnosticType.setForeground(new java.awt.Color(0, 0, 139));
        diagnosticType.setText("Diagnostic Type:");
        panelRound1.add(diagnosticType, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 332, -1, -1));

        procedureTypeTextField.setBackground(new java.awt.Color(255, 254, 238));
        procedureTypeTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        procedureTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procedureTypeTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(procedureTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 144, 100, -1));

        jPanel2.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 430, 380));

        panelRound2.setBackground(new java.awt.Color(211, 221, 255));
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medicineID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        medicineID.setForeground(new java.awt.Color(0, 0, 139));
        medicineID.setText("Medicine ID:");
        panelRound2.add(medicineID, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 21, -1, -1));

        medicineIDTextField.setBackground(new java.awt.Color(255, 254, 238));
        medicineIDTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        medicineIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineIDTextFieldActionPerformed(evt);
            }
        });
        panelRound2.add(medicineIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 148, -1));

        medicineName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        medicineName.setForeground(new java.awt.Color(0, 0, 139));
        medicineName.setText("Medicine Name:");
        medicineName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelRound2.add(medicineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 71, -1, -1));

        medicineNameTextField.setBackground(new java.awt.Color(255, 254, 238));
        medicineNameTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        medicineNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineNameTextFieldActionPerformed(evt);
            }
        });
        panelRound2.add(medicineNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 150, -1));

        medicineDescription.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        medicineDescription.setForeground(new java.awt.Color(0, 0, 139));
        medicineDescription.setText("Medicine Description:");
        panelRound2.add(medicineDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 117, -1, -1));

        medicineDescriptionTextField.setBackground(new java.awt.Color(255, 254, 238));
        medicineDescriptionTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        medicineDescriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineDescriptionTextFieldActionPerformed(evt);
            }
        });
        panelRound2.add(medicineDescriptionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 146, 16));

        amount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        amount.setForeground(new java.awt.Color(0, 0, 139));
        amount.setText("Amount:");
        panelRound2.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 162, -1, -1));

        amountTextField.setBackground(new java.awt.Color(255, 254, 238));
        amountTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        amountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextFieldActionPerformed(evt);
            }
        });
        panelRound2.add(amountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 146, -1));

        frequency.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        frequency.setForeground(new java.awt.Color(0, 0, 139));
        frequency.setText("Frequency:");
        panelRound2.add(frequency, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        frequencyTextField.setBackground(new java.awt.Color(255, 254, 238));
        frequencyTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        frequencyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frequencyTextFieldActionPerformed(evt);
            }
        });
        panelRound2.add(frequencyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 150, -1));

        providerTextField.setBackground(new java.awt.Color(255, 254, 238));
        providerTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        providerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providerTextFieldActionPerformed(evt);
            }
        });
        panelRound2.add(providerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 150, -1));

        provider.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        provider.setForeground(new java.awt.Color(0, 0, 139));
        provider.setText("Provider:");
        panelRound2.add(provider, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        tabletDosage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tabletDosage.setForeground(new java.awt.Color(0, 0, 139));
        tabletDosage.setText("Dosage:");
        panelRound2.add(tabletDosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        tabletDosageTextField.setBackground(new java.awt.Color(255, 254, 238));
        tabletDosageTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        tabletDosageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabletDosageTextFieldActionPerformed(evt);
            }
        });
        panelRound2.add(tabletDosageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 150, -1));

        liquidVolume.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        liquidVolume.setForeground(new java.awt.Color(0, 0, 139));
        liquidVolume.setText("Volume:");
        panelRound2.add(liquidVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        liquidVolumeTextField.setBackground(new java.awt.Color(255, 254, 238));
        liquidVolumeTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        liquidVolumeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liquidVolumeTextFieldActionPerformed(evt);
            }
        });
        panelRound2.add(liquidVolumeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 150, -1));

        jPanel2.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 370, 380));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 1160, 160));

        customPanelButton1.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton1.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton1.setText(" A D D");
        customPanelButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customPanelButton1.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton1.setRadius(20);
        customPanelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(customPanelButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 160, 130, 70));

        customPanelButton2.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton2.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton2.setText("E D I T");
        customPanelButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customPanelButton2.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton2.setRadius(20);
        customPanelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(customPanelButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 250, 130, 70));

        customPanelButton3.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton3.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton3.setText("R E F R E S H");
        customPanelButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customPanelButton3.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton3.setRadius(20);
        customPanelButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(customPanelButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 340, 130, 80));

        customPanelButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139), 2));
        customPanelButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/logOffIcon.png"))); // NOI18N
        customPanelButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(customPanelButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 170, -1, -1));

        customPanelButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139), 2));
        customPanelButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/homeIcon.png"))); // NOI18N
        customPanelButton4.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(customPanelButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 30, -1, -1));

        customPanelButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139), 2));
        customPanelButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/infoIcon.png"))); // NOI18N
        customPanelButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(customPanelButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/procedureAndMedicineIcon.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 710, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 900));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void patientIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIDTextFieldActionPerformed

    private void procedureDescriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procedureDescriptionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procedureDescriptionTextFieldActionPerformed

    private void procedureIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procedureIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procedureIDTextFieldActionPerformed

    private void timeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTextFieldActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void medicineIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineIDTextFieldActionPerformed

    private void medicineDescriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineDescriptionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineDescriptionTextFieldActionPerformed

    private void medicineNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineNameTextFieldActionPerformed

    private void surgeonTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surgeonTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surgeonTextFieldActionPerformed

    private void specialistTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialistTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialistTextFieldActionPerformed

    private void amountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTextFieldActionPerformed

    private void frequencyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frequencyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frequencyTextFieldActionPerformed

    private void providerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_providerTextFieldActionPerformed

    private void tabletDosageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabletDosageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabletDosageTextFieldActionPerformed

    private void liquidVolumeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liquidVolumeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liquidVolumeTextFieldActionPerformed

    private void procedureTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procedureTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procedureTypeTextFieldActionPerformed

    private void customPanelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton1ActionPerformed
//Retrieving values from textfields
        String value1 = patientIDTextField.getText();
        int value2 = Integer.parseInt(procedureIDTextField.getText());
        String value3 = dateTextField.getText();
        String value4 = timeTextField.getText();
        String value5 = procedureTypeTextField.getText();
        String value6 = procedureDescriptionTextField.getText();
        //Handling empty fields for surgeon, specialist and diagnostic type
        String value7; 
        if(surgeonTextField.getText().equals("")){
            value7 = "No Info";
        }
        else{
            value7 = surgeonTextField.getText();

        }
        String value8 ;
        if(specialistTextField.getText().equals("")){
            value8 = "No Info";
        }
        else{
            value8 = specialistTextField.getText();
        }
        String value9;
        if(diagnosticTypeTextField.getText().equals("")){
            value9 = "No Info";
        }
        else{
            value9 = diagnosticTypeTextField.getText();
        }
        //Retrieving values from textfields
        int value10 = Integer.parseInt(medicineIDTextField.getText());
        String value11 =  medicineNameTextField.getText();
        String value12 = medicineDescriptionTextField.getText();
        int value13 = Integer.parseInt(amountTextField.getText());
        String value14 = frequencyTextField.getText();
        String value15 = providerTextField.getText();
        //Handling empty fields for tablet dosage and liquid volume
        String value16;
        if(tabletDosageTextField.getText().equals("")){
            value16 = "No Info";
        }
        else {
            value16 = tabletDosageTextField.getText();
        }
        String value17;
        if(liquidVolumeTextField.getText().equals("")){
            value17 = "No Info";
        }
        else {
            value17 = liquidVolumeTextField.getText();
        }
       
        //Creating instances for the classes
        Procedure procedure1 = new Procedure(value1, value2, value3, value4, value5, value6);
        
        Surgical surgical1 = new Surgical(value1,value2,value3,value4,value5,value6,value7);
        
        Diagnostic diagnostic1 = new Diagnostic(value1,value2,value3,value4,value5,value6,value8,value9);       
        
        Medicine medicine1 = new Medicine(value10,value11,value12,value13,value14,value15);
                
        Tablet tablet1 = new Tablet(value10,value11,value12,value13,value14,value15,value16);
                
        Liquid liquid1 = new Liquid(value10,value11,value12,value13,value14,value15,value17);
         
        //Construct a string with the combined values
        String adding = "\n" + procedure1.getPatientId() + "," + procedure1.getProcedureId() + "," + procedure1.getDate() + "," + procedure1.getTime() + "," + procedure1.getProcedureType() +  "," + procedure1.getProcedureDescription() + "," 
                        + surgical1.getSurgeon() + "," + diagnostic1.getSpecialist() + "," + diagnostic1.getDiagnosticType() + "," + medicine1.getMedicineId() + "," 
                        + medicine1.getMedicineName() + "," + medicine1.getMedicineDescription() + "," + medicine1.getAmount() + "," + medicine1.getFrequency() + "," + medicine1.getProvider() + "," 
                        + tablet1.getDosage() + "," + liquid1.getVolume(); 

        //Write the combined values to a file
         String filePath = "C:\\Users\\Rayyan\\Desktop\\ProcedureMedicine.txt"; 
         try {
             //Write "adding" string to a file at the specified file path
             Files.write(Paths.get(filePath), adding.getBytes(), StandardOpenOption.APPEND);

         } catch (IOException ex) {
           //If an exception occurs during the file writing process, print the stack trace
            ex.printStackTrace();
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_customPanelButton1ActionPerformed

    private void customPanelButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton2ActionPerformed
//File path to read the data
        String filePath = "C:\\Users\\Rayyan\\Desktop\\ProcedureMedicine.txt"; 
        File file = new File(filePath); 

        try {
            //Reading the file
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim(); 
            String[] columnsName = firstLine.split(",");
            //Setting up the table model
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); 
            model.setColumnIdentifiers(columnsName);
            model.setRowCount(0);
            //Populate the table model with data
            Object[] tableLines = br.lines().toArray(); 
            for (int i = 0; i < tableLines.length; i++){
                String line= tableLines[i].toString().trim();
                String[] dataRow = line.split(","); 
                model.addRow(dataRow);
            }
            
        } catch (Exception ex) {
          //If an exception occurs during the file reading process, log the exception details
            Logger.getLogger(ProcedureAndMedicineForm.class.getName()).log(Level.SEVERE, null, ex);
        }        
        // TODO add your handling code here:        
        // TODO add your handling code here:
    }//GEN-LAST:event_customPanelButton2ActionPerformed

    private void customPanelButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton3ActionPerformed
 //File path to read the data
        String filePath = "C:\\Users\\Rayyan\\Desktop\\ProcedureMedicine.txt"; 
        File file = new File(filePath); 

        try {
            //Reading the file
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim(); 
            String[] columnsName = firstLine.split(",");
            //Setting up the table model
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); 
            model.setColumnIdentifiers(columnsName);
            model.setRowCount(0);
            //Populate the table model with data
            Object[] tableLines = br.lines().toArray(); 
            for (int i = 0; i < tableLines.length; i++){
                String line= tableLines[i].toString().trim();
                String[] dataRow = line.split(","); 
                model.addRow(dataRow);
            }
            
        } catch (Exception ex) {
          //If an exception occurs during the file reading process, log the exception details
            Logger.getLogger(ProcedureAndMedicineForm.class.getName()).log(Level.SEVERE, null, ex);
        }        
        // TODO add your handling code here:        
        // TODO add your handling code here:
    }//GEN-LAST:event_customPanelButton3ActionPerformed

    private void customPanelButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton4ActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_customPanelButton4ActionPerformed

    private void customPanelButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton5ActionPerformed
        new MedicalHistoryForm().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_customPanelButton5ActionPerformed

    private void customPanelButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton6ActionPerformed
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customPanelButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcedureAndMedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcedureAndMedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcedureAndMedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcedureAndMedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcedureAndMedicineForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amountTextField;
    private emr.system.customComponents.CustomPanelButton customPanelButton1;
    private emr.system.customComponents.CustomPanelButton customPanelButton2;
    private emr.system.customComponents.CustomPanelButton customPanelButton3;
    private emr.system.customComponents.CustomPanelButton customPanelButton4;
    private emr.system.customComponents.CustomPanelButton customPanelButton5;
    private emr.system.customComponents.CustomPanelButton customPanelButton6;
    private javax.swing.JLabel date;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel diagnosticType;
    private javax.swing.JTextField diagnosticTypeTextField;
    private javax.swing.JLabel frequency;
    private javax.swing.JTextField frequencyTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private emr.system.customComponents.CustomTable jTable1;
    private javax.swing.JLabel liquidVolume;
    private javax.swing.JTextField liquidVolumeTextField;
    private javax.swing.JLabel medicineDescription;
    private javax.swing.JTextField medicineDescriptionTextField;
    private javax.swing.JLabel medicineID;
    private javax.swing.JTextField medicineIDTextField;
    private javax.swing.JLabel medicineName;
    private javax.swing.JTextField medicineNameTextField;
    private emr.system.PanelRound panelRound1;
    private emr.system.PanelRound panelRound2;
    private javax.swing.JLabel patientID;
    private javax.swing.JTextField patientIDTextField;
    private javax.swing.JLabel procedureDescription;
    private javax.swing.JTextField procedureDescriptionTextField;
    private javax.swing.JLabel procedureID;
    private javax.swing.JTextField procedureIDTextField;
    private javax.swing.JLabel procedureType;
    private javax.swing.JTextField procedureTypeTextField;
    private javax.swing.JLabel provider;
    private javax.swing.JTextField providerTextField;
    private javax.swing.JLabel specialist;
    private javax.swing.JTextField specialistTextField;
    private javax.swing.JLabel surgeon;
    private javax.swing.JTextField surgeonTextField;
    private javax.swing.JLabel tabletDosage;
    private javax.swing.JTextField tabletDosageTextField;
    private javax.swing.JLabel time;
    private javax.swing.JTextField timeTextField;
    // End of variables declaration//GEN-END:variables
}
