/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emr.system;
import emr.system.classes.SurgicalTreatment;
import emr.system.classes.MedicationTreatment;
import emr.system.classes.Psychotherapy;
import emr.system.classes.PhysicalTherapy;
import emr.system.classes.TreatmentCourse;
import emr.system.customComponents.CustomTable;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;


/**
 *
 * @author Rayyan
 */
public class TreatmentCourseForm extends javax.swing.JFrame {

    /**
     * Creates new form TreatmentCourse
     */
    public TreatmentCourseForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new emr.system.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        riskTextField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        surgeryTypeTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        surgeryDateTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        surgicalSuitTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        durationOfHospitalizationToTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        preOperativePreparationTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        chiefSurgeonTextField = new javax.swing.JTextField();
        anaesthesiaTextField = new javax.swing.JTextField();
        durationOfHospitalizationfromTextField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        panelRound4 = new emr.system.PanelRound();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        psychologistTextField = new javax.swing.JTextField();
        durationTextField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        panelRound3 = new emr.system.PanelRound();
        jLabel21 = new javax.swing.JLabel();
        pharmacistTextField = new javax.swing.JTextField();
        dosageTakenTextField = new javax.swing.JTextField();
        frequencyTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        panelRound2 = new emr.system.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        educationForSelfManagementTextField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        therapistTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        equipmentTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PsychotherapyTable = new emr.system.customComponents.CustomTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        PhysicalTherapyTable = new emr.system.customComponents.CustomTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        MedicationTreatmentTable = new emr.system.customComponents.CustomTable();
        panelRound6 = new emr.system.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        endDateTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        doctorInChargeTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        procedureIDTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        treatmentMedicineTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        taskNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        startDateTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        customTable1 = new emr.system.customComponents.CustomTable();
        customPanelButton1 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton2 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton3 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton4 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton5 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton7 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton8 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton9 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton10 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton11 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton12 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton6 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton13 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton14 = new emr.system.customComponents.CustomPanelButton();
        customPanelButton15 = new emr.system.customComponents.CustomPanelButton();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 254, 238));
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1300, 800));
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setPreferredSize(new java.awt.Dimension(1300, 800));
        setSize(new java.awt.Dimension(1300, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 254, 238));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));

        panelRound1.setBackground(new java.awt.Color(211, 221, 255));
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 139));
        jLabel11.setText("Surgical Treatment");
        panelRound1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 6, 150, -1));

        riskTextField.setBackground(new java.awt.Color(255, 254, 238));
        riskTextField.setText(" ");
        riskTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        riskTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(riskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 100, 20));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 139));
        jLabel29.setText("Risk:");
        panelRound1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 30, 20));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 139));
        jLabel14.setText("Surgery Type:");
        panelRound1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 84, 20));

        surgeryTypeTextField.setBackground(new java.awt.Color(255, 254, 238));
        surgeryTypeTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        surgeryTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surgeryTypeTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(surgeryTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 122, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 139));
        jLabel10.setText("Surgery Date:");
        panelRound1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 119, 114, 20));

        surgeryDateTextField.setBackground(new java.awt.Color(255, 254, 238));
        surgeryDateTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        surgeryDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surgeryDateTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(surgeryDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 120, 20));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 139));
        jLabel12.setText("Surgical Suit:");
        panelRound1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 20));

        surgicalSuitTextField.setBackground(new java.awt.Color(255, 254, 238));
        surgicalSuitTextField.setText(" ");
        surgicalSuitTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        surgicalSuitTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surgicalSuitTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(surgicalSuitTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 120, 20));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 139));
        jLabel17.setText("Day Of Hospitalization:");
        panelRound1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 151, 136, 20));

        durationOfHospitalizationToTextField.setBackground(new java.awt.Color(255, 254, 238));
        durationOfHospitalizationToTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        durationOfHospitalizationToTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationOfHospitalizationToTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(durationOfHospitalizationToTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 47, 20));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 139));
        jLabel13.setText("Pre-Operative Preparation:");
        panelRound1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 179, -1, 20));

        preOperativePreparationTextField.setBackground(new java.awt.Color(255, 254, 238));
        preOperativePreparationTextField.setText(" ");
        preOperativePreparationTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        preOperativePreparationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preOperativePreparationTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(preOperativePreparationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 120, 20));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 139));
        jLabel15.setText("Anaesthesiologist: ");
        panelRound1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 20));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 139));
        jLabel16.setText("Chief Surgeon:");
        panelRound1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 93, 100, 20));

        chiefSurgeonTextField.setBackground(new java.awt.Color(255, 254, 238));
        chiefSurgeonTextField.setText(" ");
        chiefSurgeonTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        chiefSurgeonTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiefSurgeonTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(chiefSurgeonTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 120, 20));

        anaesthesiaTextField.setBackground(new java.awt.Color(255, 254, 238));
        anaesthesiaTextField.setText(" ");
        anaesthesiaTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        anaesthesiaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anaesthesiaTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(anaesthesiaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 100, 20));

        durationOfHospitalizationfromTextField.setBackground(new java.awt.Color(255, 254, 238));
        durationOfHospitalizationfromTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        durationOfHospitalizationfromTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationOfHospitalizationfromTextFieldActionPerformed(evt);
            }
        });
        panelRound1.add(durationOfHospitalizationfromTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 46, 20));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 139));
        jLabel30.setText("-");
        panelRound1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 30, -1));

        panelRound4.setBackground(new java.awt.Color(211, 221, 255));

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 139));
        jLabel25.setText("Psychotherapy Treatment ");

        jLabel26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 139));
        jLabel26.setText("Psychologist:");

        psychologistTextField.setBackground(new java.awt.Color(255, 254, 238));
        psychologistTextField.setText(" ");
        psychologistTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        psychologistTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psychologistTextFieldActionPerformed(evt);
            }
        });

        durationTextField.setBackground(new java.awt.Color(255, 254, 238));
        durationTextField.setText(" ");
        durationTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        durationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationTextFieldActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 139));
        jLabel27.setText("Duration:");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound4Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(psychologistTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(durationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(17, 17, 17)
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psychologistTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelRound3.setBackground(new java.awt.Color(211, 221, 255));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 139));
        jLabel21.setText("Medication Treatment");

        pharmacistTextField.setBackground(new java.awt.Color(255, 254, 238));
        pharmacistTextField.setText(" ");
        pharmacistTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        pharmacistTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacistTextFieldActionPerformed(evt);
            }
        });

        dosageTakenTextField.setBackground(new java.awt.Color(255, 254, 238));
        dosageTakenTextField.setText(" ");
        dosageTakenTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        dosageTakenTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosageTakenTextFieldActionPerformed(evt);
            }
        });

        frequencyTextField.setBackground(new java.awt.Color(255, 254, 238));
        frequencyTextField.setText(" ");
        frequencyTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        frequencyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frequencyTextFieldActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 139));
        jLabel22.setText("Pharmacist:");

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 139));
        jLabel23.setText("Dosage Taken:");

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 139));
        jLabel24.setText("Frequency:");

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel21))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(dosageTakenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(36, 36, 36)
                                .addComponent(pharmacistTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frequencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel21)
                .addGap(11, 11, 11)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(pharmacistTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(frequencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(dosageTakenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panelRound2.setBackground(new java.awt.Color(211, 221, 255));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 139));
        jLabel9.setText("Physcial Treatment");

        educationForSelfManagementTextField.setBackground(new java.awt.Color(255, 254, 238));
        educationForSelfManagementTextField.setText(" ");
        educationForSelfManagementTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        educationForSelfManagementTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                educationForSelfManagementTextFieldActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 139));
        jLabel28.setText("Self Management:");

        therapistTextField.setBackground(new java.awt.Color(255, 254, 238));
        therapistTextField.setText(" ");
        therapistTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        therapistTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                therapistTextFieldActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 139));
        jLabel19.setText("Equipment:");

        equipmentTextField.setBackground(new java.awt.Color(255, 254, 238));
        equipmentTextField.setText(" ");
        equipmentTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        equipmentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentTextFieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 139));
        jLabel20.setText("Education For ");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 139));
        jLabel18.setText("Therapist:");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel9)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRound2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(51, 51, 51))
                            .addGroup(panelRound2Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(therapistTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(educationForSelfManagementTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(therapistTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelRound2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(equipmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(educationForSelfManagementTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        PsychotherapyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(PsychotherapyTable);

        PhysicalTherapyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(PhysicalTherapyTable);

        MedicationTreatmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(MedicationTreatmentTable);

        panelRound6.setBackground(new java.awt.Color(211, 221, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 139));
        jLabel2.setText("Start Date:");

        endDateTextField.setBackground(new java.awt.Color(255, 254, 238));
        endDateTextField.setText(" ");
        endDateTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        endDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endDateTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 139));
        jLabel8.setText("Doctor In Charge:");

        doctorInChargeTextField.setBackground(new java.awt.Color(255, 254, 238));
        doctorInChargeTextField.setText(" ");
        doctorInChargeTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        doctorInChargeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorInChargeTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 139));
        jLabel6.setText("Procedure ID :");

        procedureIDTextField.setBackground(new java.awt.Color(255, 254, 238));
        procedureIDTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        procedureIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procedureIDTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 139));
        jLabel7.setText("Treatment Medicine:");

        treatmentMedicineTextField.setBackground(new java.awt.Color(255, 254, 238));
        treatmentMedicineTextField.setText(" ");
        treatmentMedicineTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        treatmentMedicineTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmentMedicineTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 139));
        jLabel4.setText("Description:");

        descriptionTextField.setBackground(new java.awt.Color(255, 254, 238));
        descriptionTextField.setText(" ");
        descriptionTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        descriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTextFieldActionPerformed(evt);
            }
        });

        taskNameTextField.setBackground(new java.awt.Color(255, 254, 238));
        taskNameTextField.setText(" ");
        taskNameTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        taskNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskNameTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 139));
        jLabel3.setText("Task Name:");

        startDateTextField.setBackground(new java.awt.Color(255, 254, 238));
        startDateTextField.setText(" ");
        startDateTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 139)));
        startDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 139));
        jLabel5.setText("End Date: ");

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRound6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taskNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound6Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound6Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startDateTextField)))))
                .addGap(18, 18, 18)
                .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound6Layout.createSequentialGroup()
                        .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRound6Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doctorInChargeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound6Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(39, 39, 39)
                                .addComponent(procedureIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(treatmentMedicineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(taskNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(doctorInChargeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(procedureIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(treatmentMedicineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        customTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(customTable1);

        customPanelButton1.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton1.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton1.setText("A D D");
        customPanelButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customPanelButton1.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton1.setRadius(25);
        customPanelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton1ActionPerformed(evt);
            }
        });

        customPanelButton2.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton2.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton2.setText("E D I T");
        customPanelButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customPanelButton2.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton2.setRadius(25);
        customPanelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton2ActionPerformed(evt);
            }
        });

        customPanelButton3.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton3.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton3.setText("R E F R E S H");
        customPanelButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customPanelButton3.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton3.setRadius(25);
        customPanelButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton3ActionPerformed(evt);
            }
        });

        customPanelButton4.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton4.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton4.setText("A D D");
        customPanelButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customPanelButton4.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton4.setRadius(25);
        customPanelButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton4ActionPerformed(evt);
            }
        });

        customPanelButton5.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton5.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton5.setText("E D I T");
        customPanelButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customPanelButton5.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton5.setRadius(25);
        customPanelButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton5ActionPerformed(evt);
            }
        });

        customPanelButton7.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton7.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton7.setText("A D D");
        customPanelButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customPanelButton7.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton7.setRadius(25);
        customPanelButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton7ActionPerformed(evt);
            }
        });

        customPanelButton8.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton8.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton8.setText("E D I T");
        customPanelButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customPanelButton8.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton8.setRadius(25);
        customPanelButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton8ActionPerformed(evt);
            }
        });

        customPanelButton9.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton9.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton9.setText("R E F R E S H");
        customPanelButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customPanelButton9.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton9.setRadius(25);
        customPanelButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton9ActionPerformed(evt);
            }
        });

        customPanelButton10.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton10.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton10.setText("A D D");
        customPanelButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customPanelButton10.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton10.setRadius(25);
        customPanelButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton10ActionPerformed(evt);
            }
        });

        customPanelButton11.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton11.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton11.setText("E D I T");
        customPanelButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customPanelButton11.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton11.setRadius(25);
        customPanelButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton11ActionPerformed(evt);
            }
        });

        customPanelButton12.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton12.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton12.setText("R E F R E S H");
        customPanelButton12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customPanelButton12.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton12.setRadius(25);
        customPanelButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton12ActionPerformed(evt);
            }
        });

        customPanelButton6.setBackground(new java.awt.Color(255, 254, 238));
        customPanelButton6.setForeground(new java.awt.Color(0, 0, 139));
        customPanelButton6.setText("R E F R E S H");
        customPanelButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customPanelButton6.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton6.setRadius(25);
        customPanelButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton6ActionPerformed(evt);
            }
        });

        customPanelButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139), 2));
        customPanelButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/homeIcon.png"))); // NOI18N
        customPanelButton13.setOutlineColor(new java.awt.Color(0, 0, 139));
        customPanelButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton13ActionPerformed(evt);
            }
        });

        customPanelButton14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139), 2));
        customPanelButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/infoIcon.png"))); // NOI18N
        customPanelButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton14ActionPerformed(evt);
            }
        });

        customPanelButton15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139), 2));
        customPanelButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/logOffIcon.png"))); // NOI18N
        customPanelButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPanelButton15ActionPerformed(evt);
            }
        });

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emr/system/icons/treatmentCourseIcon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(customPanelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(customPanelButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(customPanelButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(customPanelButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(customPanelButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(customPanelButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(customPanelButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(customPanelButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(customPanelButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(customPanelButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(customPanelButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(customPanelButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customPanelButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customPanelButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customPanelButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addGap(12, 12, 12)
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(customPanelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(customPanelButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(customPanelButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(customPanelButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(customPanelButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(customPanelButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customPanelButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customPanelButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customPanelButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customPanelButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customPanelButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customPanelButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customPanelButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customPanelButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customPanelButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(976, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 1770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateTextFieldActionPerformed

    private void taskNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskNameTextFieldActionPerformed

    private void descriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionTextFieldActionPerformed

    private void treatmentMedicineTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatmentMedicineTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treatmentMedicineTextFieldActionPerformed

    private void procedureIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procedureIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procedureIDTextFieldActionPerformed

    private void doctorInChargeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorInChargeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorInChargeTextFieldActionPerformed

    private void endDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endDateTextFieldActionPerformed

    private void equipmentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentTextFieldActionPerformed

    private void therapistTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_therapistTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_therapistTextFieldActionPerformed

    private void educationForSelfManagementTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_educationForSelfManagementTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_educationForSelfManagementTextFieldActionPerformed

    private void frequencyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frequencyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frequencyTextFieldActionPerformed

    private void dosageTakenTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosageTakenTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosageTakenTextFieldActionPerformed

    private void pharmacistTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacistTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pharmacistTextFieldActionPerformed

    private void durationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationTextFieldActionPerformed

    private void psychologistTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psychologistTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psychologistTextFieldActionPerformed

    private void durationOfHospitalizationfromTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationOfHospitalizationfromTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationOfHospitalizationfromTextFieldActionPerformed

    private void anaesthesiaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anaesthesiaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anaesthesiaTextFieldActionPerformed

    private void chiefSurgeonTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiefSurgeonTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chiefSurgeonTextFieldActionPerformed

    private void preOperativePreparationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preOperativePreparationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preOperativePreparationTextFieldActionPerformed

    private void durationOfHospitalizationToTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationOfHospitalizationToTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationOfHospitalizationToTextFieldActionPerformed

    private void surgicalSuitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surgicalSuitTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surgicalSuitTextFieldActionPerformed

    private void surgeryDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surgeryDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surgeryDateTextFieldActionPerformed

    private void surgeryTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surgeryTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surgeryTypeTextFieldActionPerformed

    private void riskTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riskTextFieldActionPerformed

    private void customPanelButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton2ActionPerformed
        String filePath = "C:\\Users\\Rayyan\\Desktop\\SurgicalTreatment.txt";
        File file = new File(filePath);
        try{
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write("PatientID,TaskName,ProcedureID,StartDate,EndDate,DoctorInCharge,Description,TMedicine,SurgeyType,SurgeyDate,SurgicalSuit,DurationOfHospitalization,PreOperativePreperation,ChiefSurgeon,Anaesthesia");
            bw.newLine();

            for(int i =0; i < customTable1.getRowCount(); i++){
                for(int j = 0; j < customTable1.getColumnCount(); j++){
                    bw.write(customTable1.getValueAt(i, j).toString()+ ",");

         }
                bw.newLine();

            }
            bw.close();
            fw.close();

        }
        catch(IOException ex){
            System.out.println("Errror");
        }
    }//GEN-LAST:event_customPanelButton2ActionPerformed

    private void customPanelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton1ActionPerformed
   // TODO add your handling code here:
         // TODO add your handling code here:
        String value1 = surgeryTypeTextField.getText();
        String value2 = surgeryDateTextField.getText();
        String value3 = surgicalSuitTextField.getText();
        String value4 = durationOfHospitalizationfromTextField.getText()+"-"+durationOfHospitalizationToTextField.getText();
        String value5= preOperativePreparationTextField.getText();
        String value6= chiefSurgeonTextField.getText();
        String value7= anaesthesiaTextField.getText();
        int value8 = 001;
        String value9= taskNameTextField.getText();
        String value10= descriptionTextField.getText();
        String value11= treatmentMedicineTextField.getText();
        String value12 = startDateTextField.getText();
        String value13 = endDateTextField.getText();
        int value14 = Integer.parseInt(procedureIDTextField.getText());
        String value15 = doctorInChargeTextField.getText();
        String value25 =riskTextField.getText();

        SurgicalTreatment ST1 = new SurgicalTreatment(value9,value14,value12,value13,value15,value8,value10,value11,value2,value1,value3,value7,value5,value6,value25,value4);
        String value81 = String.valueOf(value8);
        String value141 = String.valueOf(value14);
        
       
        
        String adding = "\n" + ST1.getPatientID()  + "," +ST1.getTaskName() + "," + ST1.getProcedureID() + "," + ST1.getStartDate() + "," + ST1.getEndDate() + "," + ST1.getDoctorInCharge() + "," + ST1.getDescription() + "," +ST1.getTMedicine() + "," + 
                ST1.getSurgeryType() + "," + ST1.getSurgeryDate() + "," + ST1.getSurgerySuit() + "," + ST1.getDurationOfHospitalization() + "," + ST1.getPreOperativePrepaeration() + "," + ST1.getChiefSurgeon() + "," +ST1.getAnaesthesia() + ","+ ST1.getRisk() + "," ;

        String filePath = "C:\\Users\\Rayyan\\Desktop\\SurgicalTreatment.txt";
        try {
               Files.write(Paths.get(filePath), adding.getBytes(), StandardOpenOption.APPEND);

        } catch (IOException ex) {
            ex.printStackTrace();
        }  
    }//GEN-LAST:event_customPanelButton1ActionPerformed

    private void customPanelButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton3ActionPerformed
        String filePath = "C:\\Users\\Rayyan\\Desktop\\SurgicalTreatment.txt";
        File file = new File(filePath);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)customTable1.getModel();
            model.setColumnIdentifiers(columnsName);
            model.setRowCount(0);
            Object[] tableLines = br.lines().toArray();
            for (int i = 0; i < tableLines.length; i++){
                String line= tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);

            }
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(TreatmentCourseForm.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_customPanelButton3ActionPerformed

    private void customPanelButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton4ActionPerformed
     // TODO add your handling code here:
        int value8= 001;
        String value9= taskNameTextField.getText();
        String value10= descriptionTextField.getText();
        String value11= treatmentMedicineTextField.getText();
        String value12 = startDateTextField.getText();
        String value13 = endDateTextField.getText();
        int value14 = Integer.parseInt(procedureIDTextField.getText());
        String value15 = doctorInChargeTextField.getText();
        String value16 = therapistTextField.getText();
        String value17 = equipmentTextField.getText();
        String value18 = educationForSelfManagementTextField.getText();
        String value81 = String.valueOf(value8);
        String value141 = String.valueOf(value14);
       
        PhysicalTherapy PHT1 = new PhysicalTherapy(value9,value14,value12,value13,value15,value8,value10,value11,value16,value17,value18);
        
        

        String adding = "\n" + PHT1.getPatientID()  + "," + PHT1.getTaskName() + "," + PHT1.getProcedureID() + "," + PHT1.getStartDate() + "," + PHT1.getEndDate() + "," + PHT1.getDoctorInCharge() + "," + PHT1.getDescription() + "," +PHT1.getTMedicine() + "," + 
                PHT1.getTherapist() + "," + PHT1.getEquipment() + "," + PHT1.getEducationForSelfManagement() + "," ;

        String filePath = "C:\\Users\\Rayyan\\Desktop\\PhysicalTherapy.txt";
        try {
            Files.write(Paths.get(filePath), adding.getBytes(), StandardOpenOption.APPEND);

        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_customPanelButton4ActionPerformed

    private void customPanelButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton5ActionPerformed
      // TODO add your handling code here:
        String filePath = "C:\\Users\\Rayyan\\Desktop\\PhysicalTherapy.txt";
        File file = new File(filePath);
        try{
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write("PatientID,TaskName,ProcedureID,StartDate,EndDate,Medication History,DoctorInCharge,Description,TMedicine,Therapist,Equipment.EducationForSelfManagement");
            bw.newLine();

            for(int i =0; i < PhysicalTherapyTable.getRowCount(); i++){
                for(int j = 0; j < PhysicalTherapyTable.getColumnCount(); j++){
                    bw.write(PhysicalTherapyTable.getValueAt(i, j).toString()+ ",");

                }
                bw.newLine();

            }
            bw.close();
            fw.close();

        }
        catch(IOException ex){
            System.out.println("Errror");
        }  
    }//GEN-LAST:event_customPanelButton5ActionPerformed

    private void customPanelButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton7ActionPerformed
         // TODO add your handling code here:
        int value8= 001;
        String value9= taskNameTextField.getText();
        String value10= descriptionTextField.getText();
        String value11= treatmentMedicineTextField.getText();
        String value12 = startDateTextField.getText();
        String value13 = endDateTextField.getText();
        int value14 = Integer.parseInt(procedureIDTextField.getText());
        String value15 = doctorInChargeTextField.getText();
        String value19 = pharmacistTextField.getText();
        String value20 = dosageTakenTextField.getText();
        String value21 =frequencyTextField.getText();
        String value81 = String.valueOf(value8);
        String value141 = String.valueOf(value14);
        MedicationTreatment MT1= new MedicationTreatment(value9,value14,value12,value13,value15,value8,value10,value11,value20,value19,value21);
        
        String adding = "\n" + MT1.getPatientID()  + "," + MT1.getTaskName() + "," + MT1.getProcedureID() + "," + MT1.getStartDate() + "," + MT1.getEndDate() + "," + MT1.getDoctorInCharge() + "," + MT1.getDescription() + "," +MT1.getTMedicine()  + "," + value20 + "," + value19 + "," + value21 + "," ;

        String filePath = "C:\\Users\\Rayyan\\Desktop\\MedicationTreatment.txt";
        try {
            Files.write(Paths.get(filePath), adding.getBytes(), StandardOpenOption.APPEND);

        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_customPanelButton7ActionPerformed

    private void customPanelButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton8ActionPerformed
        String filePath = "C:\\Users\\Rayyan\\Desktop\\MedicationTreatment.txt";
        File file = new File(filePath);
        try{
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write("PatientID,TaskName,ProcedureID,StartDate,EndDate,DoctorInCharge,Description,TMedicine,DosageTaken,Pharmacist,Frequency");
            bw.newLine();

            for(int i =0; i < MedicationTreatmentTable.getRowCount(); i++){
                for(int j = 0; j < MedicationTreatmentTable.getColumnCount(); j++){
                    bw.write(MedicationTreatmentTable.getValueAt(i, j).toString()+ ",");

                }
                bw.newLine();

            }
            bw.close();
            fw.close();

        }
        catch(IOException ex){
            System.out.println("Errror");
        }
    }//GEN-LAST:event_customPanelButton8ActionPerformed

    private void customPanelButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton9ActionPerformed
     // TODO add your handling code here:
        String filePath = "C:\\Users\\Rayyan\\Desktop\\MedicationTreatment.txt";
        File file = new File(filePath);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)MedicationTreatmentTable.getModel();
            model.setColumnIdentifiers(columnsName);
            model.setRowCount(0);
            Object[] tableLines = br.lines().toArray();
            for (int i = 0; i < tableLines.length; i++){
                String line= tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);

            }
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(TreatmentCourseForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_customPanelButton9ActionPerformed

    private void customPanelButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton10ActionPerformed
        // TODO add your handling code here:
        int value8= 001; 
        String value9= taskNameTextField.getText();
        String value10= descriptionTextField.getText();
        String value11= treatmentMedicineTextField.getText();
        String value12 = startDateTextField.getText();
        String value13 = endDateTextField.getText();
        int value14 = Integer.parseInt(procedureIDTextField.getText());
        String value15 = doctorInChargeTextField.getText();
        String value22 = psychologistTextField.getText();
        String value23 = durationTextField.getText();
        String value81 = String.valueOf(value8);
        String value141 = String.valueOf(value14);

        Psychotherapy PST1 = new Psychotherapy (value9,value14,value12,value13,value15,value8,value10,value11,value22,value23);
        
        String adding = "\n" + PST1.getPatientID()  + "," + PST1.getTaskName() + "," + PST1.getProcedureID() + "," + PST1.getStartDate() + "," +PST1.getEndDate() + "," + PST1.getDoctorInCharge() + "," + PST1.getDescription() + "," +PST1.getTMedicine() + "," + 
                PST1.getPsychologist() + "," + PST1.getDuration() + ",";

        String filePath = "C:\\Users\\Rayyan\\Desktop\\Psychotherapy.txt";
        try {
            Files.write(Paths.get(filePath), adding.getBytes(), StandardOpenOption.APPEND);

        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_customPanelButton10ActionPerformed

    private void customPanelButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton11ActionPerformed
      // TODO add your handling code here:
        String filePath = "C:\\Users\\Rayyan\\Desktop\\Psychotherapy.txt";
        File file = new File(filePath);
        try{
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write("PatientID,TaskName,ProcedureID,StartDate,EndDate,Medication History,DoctorInCharge,Description,TMedicine,Psychologist,Duration");
            bw.newLine();

            for(int i =0; i <PsychotherapyTable.getRowCount(); i++){
                for(int j = 0; j < PsychotherapyTable.getColumnCount(); j++){
                    bw.write(PsychotherapyTable.getValueAt(i, j).toString()+ ",");

                }
                bw.newLine();

            }
            bw.close();
            fw.close();

        }
        catch(IOException ex){
            System.out.println("Errror");
        }
    }//GEN-LAST:event_customPanelButton11ActionPerformed

    private void customPanelButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton12ActionPerformed
     
        String filePath = "C:\\Users\\Rayyan\\Desktop\\Psychotherapy.txt";
        File file = new File(filePath);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)PsychotherapyTable.getModel();
            model.setColumnIdentifiers(columnsName);
            model.setRowCount(0);
            Object[] tableLines = br.lines().toArray();
            for (int i = 0; i < tableLines.length; i++){
                String line= tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);

            }
            
        } catch (Exception ex) {
            Logger.getLogger(TreatmentCourseForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_customPanelButton12ActionPerformed

    private void customPanelButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton6ActionPerformed
      String filePath = "C:\\Users\\Rayyan\\Desktop\\PhysicalTherapy.txt";
        File file = new File(filePath);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)PhysicalTherapyTable.getModel();
            model.setColumnIdentifiers(columnsName);
            model.setRowCount(0);
            Object[] tableLines = br.lines().toArray();
            for (int i = 0; i < tableLines.length; i++){
                String line= tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);

            }
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(TreatmentCourseForm.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_customPanelButton6ActionPerformed

    private void customPanelButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton14ActionPerformed
        new MedicalHistoryForm().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_customPanelButton14ActionPerformed

    private void customPanelButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton15ActionPerformed
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customPanelButton15ActionPerformed

    private void customPanelButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPanelButton13ActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customPanelButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TreatmentCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TreatmentCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TreatmentCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreatmentCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TreatmentCourseForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private emr.system.customComponents.CustomTable MedicationTreatmentTable;
    private emr.system.customComponents.CustomTable PhysicalTherapyTable;
    private emr.system.customComponents.CustomTable PsychotherapyTable;
    private javax.swing.JTextField anaesthesiaTextField;
    private javax.swing.JTextField chiefSurgeonTextField;
    private emr.system.customComponents.CustomPanelButton customPanelButton1;
    private emr.system.customComponents.CustomPanelButton customPanelButton10;
    private emr.system.customComponents.CustomPanelButton customPanelButton11;
    private emr.system.customComponents.CustomPanelButton customPanelButton12;
    private emr.system.customComponents.CustomPanelButton customPanelButton13;
    private emr.system.customComponents.CustomPanelButton customPanelButton14;
    private emr.system.customComponents.CustomPanelButton customPanelButton15;
    private emr.system.customComponents.CustomPanelButton customPanelButton2;
    private emr.system.customComponents.CustomPanelButton customPanelButton3;
    private emr.system.customComponents.CustomPanelButton customPanelButton4;
    private emr.system.customComponents.CustomPanelButton customPanelButton5;
    private emr.system.customComponents.CustomPanelButton customPanelButton6;
    private emr.system.customComponents.CustomPanelButton customPanelButton7;
    private emr.system.customComponents.CustomPanelButton customPanelButton8;
    private emr.system.customComponents.CustomPanelButton customPanelButton9;
    private emr.system.customComponents.CustomTable customTable1;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JTextField doctorInChargeTextField;
    private javax.swing.JTextField dosageTakenTextField;
    private javax.swing.JTextField durationOfHospitalizationToTextField;
    private javax.swing.JTextField durationOfHospitalizationfromTextField;
    private javax.swing.JTextField durationTextField;
    private javax.swing.JTextField educationForSelfManagementTextField;
    private javax.swing.JTextField endDateTextField;
    private javax.swing.JTextField equipmentTextField;
    private javax.swing.JTextField frequencyTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private emr.system.PanelRound panelRound1;
    private emr.system.PanelRound panelRound2;
    private emr.system.PanelRound panelRound3;
    private emr.system.PanelRound panelRound4;
    private emr.system.PanelRound panelRound6;
    private javax.swing.JTextField pharmacistTextField;
    private javax.swing.JTextField preOperativePreparationTextField;
    private javax.swing.JTextField procedureIDTextField;
    private javax.swing.JTextField psychologistTextField;
    private javax.swing.JTextField riskTextField;
    private javax.swing.JTextField startDateTextField;
    private javax.swing.JTextField surgeryDateTextField;
    private javax.swing.JTextField surgeryTypeTextField;
    private javax.swing.JTextField surgicalSuitTextField;
    private javax.swing.JTextField taskNameTextField;
    private javax.swing.JTextField therapistTextField;
    private javax.swing.JTextField treatmentMedicineTextField;
    // End of variables declaration//GEN-END:variables
}



